import {
	Timezone,
	TimezonePicklist,
	Timezone2DimensionArray,
} from '@/types/index.js';
/**
 * @name timezone2DimensionArray
 * @description This is a 2-dimensional array. Each element is an array that contains 3 elements: [["time", "abbr", "offset"], ...] which represents a timezone.
 * @type {[string, string, number]}
 * @type {string} time
 * @type {string} abbr
 * @type {number} offset
 * @readonly
 * @version 0.0.1
 * @example
 * e.g.
 * `["Dateline Standard Time", "DST", -12]`
 * `["Hawaiian Standard Time", "HST", -10]`
 * `["UTC-11", "U", -11]`
 */

export const timezone2DimensionArray: Timezone2DimensionArray = [
	['Dateline Standard Time', 'DST', -12],
	['UTC-11', 'U', -11],
	['Hawaiian Standard Time', 'HST', -10],
	['Alaskan Standard Time', 'AKDT', -8],
	['Pacific Standard Time (Mexico)', 'PDT', -7],
	['Pacific Daylight Time', 'PDT', -7],
	['Pacific Standard Time', 'PST', -8],
	['US Mountain Standard Time', 'UMST', -7],
	['Mountain Standard Time (Mexico)', 'MDT', -6],
	['Mountain Standard Time', 'MDT', -6],
	['Central America Standard Time', 'CAST', -6],
	['Central Standard Time', 'CDT', -5],
	['Central Standard Time (Mexico)', 'CDT', -5],
	['Canada Central Standard Time', 'CCST', -6],
	['SA Pacific Standard Time', 'SPST', -5],
	['Eastern Standard Time', 'EST', -5],
	['Eastern Daylight Time', 'EDT', -4],
	['US Eastern Standard Time', 'UEDT', -5],
	['Venezuela Standard Time', 'VST', -4.5],
	['Paraguay Standard Time', 'PYT', -4],
	['Atlantic Standard Time', 'ADT', -3],
	['Central Brazilian Standard Time', 'CBST', -4],
	['SA Western Standard Time', 'SWST', -4],
	['Pacific SA Standard Time', 'PSST', -4],
	['Newfoundland Standard Time', 'NDT', -2.5],
	['E. South America Standard Time', 'ESAST', -3],
	['Argentina Standard Time', 'AST', -3],
	['SA Eastern Standard Time', 'SEST', -3],
	['Greenland Standard Time', 'GDT', -3],
	['Montevideo Standard Time', 'MST', -3],
	['Bahia Standard Time', 'BST', -3],
	['UTC-02', 'U', -2],
	['Mid-Atlantic Standard Time', 'MDT', -1],
	['Azores Standard Time', 'ADT', 0],
	['Cape Verde Standard Time', 'CVST', -1],
	['Morocco Standard Time', 'MDT', 1],
	['UTC', 'UTC', 0],
	['GMT Standard Time', 'GMT', 0],
	['British Summer Time', 'BST', 1],
	['GMT Standard Time', 'GDT', 1],
	['Greenwich Standard Time', 'GST', 0],
	['W. Europe Standard Time', 'WEDT', 2],
	['Central Europe Standard Time', 'CEDT', 2],
	['Romance Standard Time', 'RDT', 2],
	['Central European Standard Time', 'CEDT', 2],
	['W. Central Africa Standard Time', 'WCAST', 1],
	['Namibia Standard Time', 'NST', 1],
	['GTB Standard Time', 'GDT', 3],
	['Middle East Standard Time', 'MEDT', 3],
	['Egypt Standard Time', 'EST', 2],
	['Syria Standard Time', 'SDT', 3],
	['E. Europe Standard Time', 'EEDT', 3],
	['South Africa Standard Time', 'SAST', 2],
	['FLE Standard Time', 'FDT', 3],
	['Turkey Standard Time', 'TDT', 3],
	['Israel Standard Time', 'JDT', 3],
	['Libya Standard Time', 'LST', 2],
	['Jordan Standard Time', 'JST', 3],
	['Arabic Standard Time', 'AST', 3],
	['Kaliningrad Standard Time', 'KST', 3],
	['Arab Standard Time', 'AST', 3],
	['E. Africa Standard Time', 'EAST', 3],
	['Moscow Standard Time', 'MSK', 3],
	['Samara Time', 'SAMT', 4],
	['Iran Standard Time', 'IDT', 4.5],
	['Arabian Standard Time', 'AST', 4],
	['Azerbaijan Standard Time', 'ADT', 5],
	['Mauritius Standard Time', 'MST', 4],
	['Georgian Standard Time', 'GET', 4],
	['Caucasus Standard Time', 'CST', 4],
	['Afghanistan Standard Time', 'AST', 4.5],
	['West Asia Standard Time', 'WAST', 5],
	['Yekaterinburg Time', 'YEKT', 5],
	['Pakistan Standard Time', 'PKT', 5],
	['India Standard Time', 'IST', 5.5],
	['Sri Lanka Standard Time', 'SLST', 5.5],
	['Nepal Standard Time', 'NST', 5.75],
	['Central Asia Standard Time', 'CAST', 6],
	['Bangladesh Standard Time', 'BST', 6],
	['Myanmar Standard Time', 'MST', 6.5],
	['SE Asia Standard Time', 'SAST', 7],
	['N. Central Asia Standard Time', 'NCAST', 7],
	['China Standard Time', 'CST', 8],
	['North Asia Standard Time', 'NAST', 8],
	['Singapore Standard Time', 'MPST', 8],
	['W. Australia Standard Time', 'WAST', 8],
	['Taipei Standard Time', 'TST', 8],
	['Ulaanbaatar Standard Time', 'UST', 8],
	['North Asia East Standard Time', 'NAEST', 8],
	['Japan Standard Time', 'JST', 9],
	['Korea Standard Time', 'KST', 9],
	['Cen. Australia Standard Time', 'CAST', 9.5],
	['AUS Central Standard Time', 'ACST', 9.5],
	['E. Australia Standard Time', 'EAST', 10],
	['AUS Eastern Standard Time', 'AEST', 10],
	['West Pacific Standard Time', 'WPST', 10],
	['Tasmania Standard Time', 'TST', 10],
	['Yakutsk Standard Time', 'YST', 9],
	['Central Pacific Standard Time', 'CPST', 11],
	['Vladivostok Standard Time', 'VST', 11],
	['New Zealand Standard Time', 'NZST', 12],
	['UTC+12', 'U', 12],
	['Fiji Standard Time', 'FST', 12],
	['Magadan Standard Time', 'MST', 12],
	['Kamchatka Standard Time', 'KDT', 13],
	['Tonga Standard Time', 'TST', 13],
	['Samoa Standard Time', 'SST', 13],
] as const;
/**
 * @name tzdata
 * @description This is a list of all timezones.
 * @type {Timezone[]}
 * @readonly
 * @version 0.0.1
 * @example
 * e.g.
 * `[{"value": "Dateline Standard Time", "abbr": "DST", "offset": -12, "isdst": false, "text": "(UTC-12:00) International Date Line West", "utc": ["Etc/GMT+12"]}]`
 * `[{"value": "UTC-11", "abbr": "U", "offset": -11, "isdst": false, "text": "(UTC-11:00) Coordinated Universal Time-11", "utc": ["Etc/GMT+11", "Pacific/Midway", "Pacific/Niue", "Pacific/Pago_Pago"]}]`
 * `[{"value": "Hawaiian Standard Time", "abbr": "HST", "offset": -10, "isdst": false, "text": "(UTC-10:00) Hawaii", "utc": ["Etc/GMT+10", "Pacific/Honolulu", "Pacific/Johnston", "Pacific/Rarotonga", "Pacific/Tahiti"]}]`
 */
export const timezone: Timezone[] = [
	{
		value: 'Dateline Standard Time',
		abbr: 'DST',
		offset: -12,
		isdst: false,
		text: '(UTC-12:00) International Date Line West',
		utc: ['Etc/GMT+12'],
	},
	{
		value: 'UTC-11',
		abbr: 'U',
		offset: -11,
		isdst: false,
		text: '(UTC-11:00) Coordinated Universal Time-11',
		utc: ['Etc/GMT+11', 'Pacific/Midway', 'Pacific/Niue', 'Pacific/Pago_Pago'],
	},
	{
		value: 'Hawaiian Standard Time',
		abbr: 'HST',
		offset: -10,
		isdst: false,
		text: '(UTC-10:00) Hawaii',
		utc: [
			'Etc/GMT+10',
			'Pacific/Honolulu',
			'Pacific/Johnston',
			'Pacific/Rarotonga',
			'Pacific/Tahiti',
		],
	},
	{
		value: 'Alaskan Standard Time',
		abbr: 'AKDT',
		offset: -8,
		isdst: true,
		text: '(UTC-09:00) Alaska',
		utc: [
			'America/Anchorage',
			'America/Juneau',
			'America/Nome',
			'America/Sitka',
			'America/Yakutat',
		],
	},
	{
		value: 'Pacific Standard Time (Mexico)',
		abbr: 'PDT',
		offset: -7,
		isdst: true,
		text: '(UTC-08:00) Baja California',
		utc: ['America/Santa_Isabel'],
	},
	{
		value: 'Pacific Daylight Time',
		abbr: 'PDT',
		offset: -7,
		isdst: true,
		text: '(UTC-07:00) Pacific Daylight Time (US & Canada)',
		utc: ['America/Los_Angeles', 'America/Tijuana', 'America/Vancouver'],
	},
	{
		value: 'Pacific Standard Time',
		abbr: 'PST',
		offset: -8,
		isdst: false,
		text: '(UTC-08:00) Pacific Standard Time (US & Canada)',
		utc: [
			'America/Los_Angeles',
			'America/Tijuana',
			'America/Vancouver',
			'PST8PDT',
		],
	},
	{
		value: 'US Mountain Standard Time',
		abbr: 'UMST',
		offset: -7,
		isdst: false,
		text: '(UTC-07:00) Arizona',
		utc: [
			'America/Creston',
			'America/Dawson',
			'America/Dawson_Creek',
			'America/Hermosillo',
			'America/Phoenix',
			'America/Whitehorse',
			'Etc/GMT+7',
		],
	},
	{
		value: 'Mountain Standard Time (Mexico)',
		abbr: 'MDT',
		offset: -6,
		isdst: true,
		text: '(UTC-07:00) Chihuahua, La Paz, Mazatlan',
		utc: ['America/Chihuahua', 'America/Mazatlan'],
	},
	{
		value: 'Mountain Standard Time',
		abbr: 'MDT',
		offset: -6,
		isdst: true,
		text: '(UTC-07:00) Mountain Time (US & Canada)',
		utc: [
			'America/Boise',
			'America/Cambridge_Bay',
			'America/Denver',
			'America/Edmonton',
			'America/Inuvik',
			'America/Ojinaga',
			'America/Yellowknife',
			'MST7MDT',
		],
	},
	{
		value: 'Central America Standard Time',
		abbr: 'CAST',
		offset: -6,
		isdst: false,
		text: '(UTC-06:00) Central America',
		utc: [
			'America/Belize',
			'America/Costa_Rica',
			'America/El_Salvador',
			'America/Guatemala',
			'America/Managua',
			'America/Tegucigalpa',
			'Etc/GMT+6',
			'Pacific/Galapagos',
		],
	},
	{
		value: 'Central Standard Time',
		abbr: 'CDT',
		offset: -5,
		isdst: true,
		text: '(UTC-06:00) Central Time (US & Canada)',
		utc: [
			'America/Chicago',
			'America/Indiana/Knox',
			'America/Indiana/Tell_City',
			'America/Matamoros',
			'America/Menominee',
			'America/North_Dakota/Beulah',
			'America/North_Dakota/Center',
			'America/North_Dakota/New_Salem',
			'America/Rainy_River',
			'America/Rankin_Inlet',
			'America/Resolute',
			'America/Winnipeg',
			'CST6CDT',
		],
	},
	{
		value: 'Central Standard Time (Mexico)',
		abbr: 'CDT',
		offset: -5,
		isdst: true,
		text: '(UTC-06:00) Guadalajara, Mexico City, Monterrey',
		utc: [
			'America/Bahia_Banderas',
			'America/Cancun',
			'America/Merida',
			'America/Mexico_City',
			'America/Monterrey',
		],
	},
	{
		value: 'Canada Central Standard Time',
		abbr: 'CCST',
		offset: -6,
		isdst: false,
		text: '(UTC-06:00) Saskatchewan',
		utc: ['America/Regina', 'America/Swift_Current'],
	},
	{
		value: 'SA Pacific Standard Time',
		abbr: 'SPST',
		offset: -5,
		isdst: false,
		text: '(UTC-05:00) Bogota, Lima, Quito',
		utc: [
			'America/Bogota',
			'America/Cayman',
			'America/Coral_Harbour',
			'America/Eirunepe',
			'America/Guayaquil',
			'America/Jamaica',
			'America/Lima',
			'America/Panama',
			'America/Rio_Branco',
			'Etc/GMT+5',
		],
	},
	{
		value: 'Eastern Standard Time',
		abbr: 'EST',
		offset: -5,
		isdst: false,
		text: '(UTC-05:00) Eastern Time (US & Canada)',
		utc: [
			'America/Detroit',
			'America/Havana',
			'America/Indiana/Petersburg',
			'America/Indiana/Vincennes',
			'America/Indiana/Winamac',
			'America/Iqaluit',
			'America/Kentucky/Monticello',
			'America/Louisville',
			'America/Montreal',
			'America/Nassau',
			'America/New_York',
			'America/Nipigon',
			'America/Pangnirtung',
			'America/Port-au-Prince',
			'America/Thunder_Bay',
			'America/Toronto',
		],
	},
	{
		value: 'Eastern Daylight Time',
		abbr: 'EDT',
		offset: -4,
		isdst: true,
		text: '(UTC-04:00) Eastern Daylight Time (US & Canada)',
		utc: [
			'America/Detroit',
			'America/Havana',
			'America/Indiana/Petersburg',
			'America/Indiana/Vincennes',
			'America/Indiana/Winamac',
			'America/Iqaluit',
			'America/Kentucky/Monticello',
			'America/Louisville',
			'America/Montreal',
			'America/Nassau',
			'America/New_York',
			'America/Nipigon',
			'America/Pangnirtung',
			'America/Port-au-Prince',
			'America/Thunder_Bay',
			'America/Toronto',
		],
	},
	{
		value: 'US Eastern Standard Time',
		abbr: 'UEDT',
		offset: -5,
		isdst: false,
		text: '(UTC-05:00) Indiana (East)',
		utc: [
			'America/Indiana/Marengo',
			'America/Indiana/Vevay',
			'America/Indianapolis',
		],
	},
	{
		value: 'Venezuela Standard Time',
		abbr: 'VST',
		offset: -4.5,
		isdst: false,
		text: '(UTC-04:30) Caracas',
		utc: ['America/Caracas'],
	},
	{
		value: 'Paraguay Standard Time',
		abbr: 'PYT',
		offset: -4,
		isdst: false,
		text: '(UTC-04:00) Asuncion',
		utc: ['America/Asuncion'],
	},
	{
		value: 'Atlantic Standard Time',
		abbr: 'ADT',
		offset: -3,
		isdst: true,
		text: '(UTC-04:00) Atlantic Time (Canada)',
		utc: [
			'America/Glace_Bay',
			'America/Goose_Bay',
			'America/Halifax',
			'America/Moncton',
			'America/Thule',
			'Atlantic/Bermuda',
		],
	},
	{
		value: 'Central Brazilian Standard Time',
		abbr: 'CBST',
		offset: -4,
		isdst: false,
		text: '(UTC-04:00) Cuiaba',
		utc: ['America/Campo_Grande', 'America/Cuiaba'],
	},
	{
		value: 'SA Western Standard Time',
		abbr: 'SWST',
		offset: -4,
		isdst: false,
		text: '(UTC-04:00) Georgetown, La Paz, Manaus, San Juan',
		utc: [
			'America/Anguilla',
			'America/Antigua',
			'America/Aruba',
			'America/Barbados',
			'America/Blanc-Sablon',
			'America/Boa_Vista',
			'America/Curacao',
			'America/Dominica',
			'America/Grand_Turk',
			'America/Grenada',
			'America/Guadeloupe',
			'America/Guyana',
			'America/Kralendijk',
			'America/La_Paz',
			'America/Lower_Princes',
			'America/Manaus',
			'America/Marigot',
			'America/Martinique',
			'America/Montserrat',
			'America/Port_of_Spain',
			'America/Porto_Velho',
			'America/Puerto_Rico',
			'America/Santo_Domingo',
			'America/St_Barthelemy',
			'America/St_Kitts',
			'America/St_Lucia',
			'America/St_Thomas',
			'America/St_Vincent',
			'America/Tortola',
			'Etc/GMT+4',
		],
	},
	{
		value: 'Pacific SA Standard Time',
		abbr: 'PSST',
		offset: -4,
		isdst: false,
		text: '(UTC-04:00) Santiago',
		utc: ['America/Santiago', 'Antarctica/Palmer'],
	},
	{
		value: 'Newfoundland Standard Time',
		abbr: 'NDT',
		offset: -2.5,
		isdst: true,
		text: '(UTC-03:30) Newfoundland',
		utc: ['America/St_Johns'],
	},
	{
		value: 'E. South America Standard Time',
		abbr: 'ESAST',
		offset: -3,
		isdst: false,
		text: '(UTC-03:00) Brasilia',
		utc: ['America/Sao_Paulo'],
	},
	{
		value: 'Argentina Standard Time',
		abbr: 'AST',
		offset: -3,
		isdst: false,
		text: '(UTC-03:00) Buenos Aires',
		utc: [
			'America/Argentina/Buenos_Aires',
			'America/Argentina/Catamarca',
			'America/Argentina/Cordoba',
			'America/Argentina/Jujuy',
			'America/Argentina/La_Rioja',
			'America/Argentina/Mendoza',
			'America/Argentina/Rio_Gallegos',
			'America/Argentina/Salta',
			'America/Argentina/San_Juan',
			'America/Argentina/San_Luis',
			'America/Argentina/Tucuman',
			'America/Argentina/Ushuaia',
			'America/Buenos_Aires',
			'America/Catamarca',
			'America/Cordoba',
			'America/Jujuy',
			'America/Mendoza',
		],
	},
	{
		value: 'SA Eastern Standard Time',
		abbr: 'SEST',
		offset: -3,
		isdst: false,
		text: '(UTC-03:00) Cayenne, Fortaleza',
		utc: [
			'America/Araguaina',
			'America/Belem',
			'America/Cayenne',
			'America/Fortaleza',
			'America/Maceio',
			'America/Paramaribo',
			'America/Recife',
			'America/Santarem',
			'Antarctica/Rothera',
			'Atlantic/Stanley',
			'Etc/GMT+3',
		],
	},
	{
		value: 'Greenland Standard Time',
		abbr: 'GDT',
		offset: -3,
		isdst: true,
		text: '(UTC-03:00) Greenland',
		utc: ['America/Godthab'],
	},
	{
		value: 'Montevideo Standard Time',
		abbr: 'MST',
		offset: -3,
		isdst: false,
		text: '(UTC-03:00) Montevideo',
		utc: ['America/Montevideo'],
	},
	{
		value: 'Bahia Standard Time',
		abbr: 'BST',
		offset: -3,
		isdst: false,
		text: '(UTC-03:00) Salvador',
		utc: ['America/Bahia'],
	},
	{
		value: 'UTC-02',
		abbr: 'U',
		offset: -2,
		isdst: false,
		text: '(UTC-02:00) Coordinated Universal Time-02',
		utc: ['America/Noronha', 'Atlantic/South_Georgia', 'Etc/GMT+2'],
	},
	{
		value: 'Mid-Atlantic Standard Time',
		abbr: 'MDT',
		offset: -1,
		isdst: true,
		text: '(UTC-02:00) Mid-Atlantic - Old',
		utc: [],
	},
	{
		value: 'Azores Standard Time',
		abbr: 'ADT',
		offset: 0,
		isdst: true,
		text: '(UTC-01:00) Azores',
		utc: ['America/Scoresbysund', 'Atlantic/Azores'],
	},
	{
		value: 'Cape Verde Standard Time',
		abbr: 'CVST',
		offset: -1,
		isdst: false,
		text: '(UTC-01:00) Cape Verde Is.',
		utc: ['Atlantic/Cape_Verde', 'Etc/GMT+1'],
	},
	{
		value: 'Morocco Standard Time',
		abbr: 'MDT',
		offset: 1,
		isdst: true,
		text: '(UTC) Casablanca',
		utc: ['Africa/Casablanca', 'Africa/El_Aaiun'],
	},
	{
		value: 'UTC',
		abbr: 'UTC',
		offset: 0,
		isdst: false,
		text: '(UTC) Coordinated Universal Time',
		utc: ['America/Danmarkshavn', 'Etc/GMT'],
	},
	{
		value: 'GMT Standard Time',
		abbr: 'GMT',
		offset: 0,
		isdst: false,
		text: '(UTC) Edinburgh, London',
		utc: [
			'Europe/Isle_of_Man',
			'Europe/Guernsey',
			'Europe/Jersey',
			'Europe/London',
		],
	},
	{
		value: 'British Summer Time',
		abbr: 'BST',
		offset: 1,
		isdst: true,
		text: '(UTC+01:00) Edinburgh, London',
		utc: [
			'Europe/Isle_of_Man',
			'Europe/Guernsey',
			'Europe/Jersey',
			'Europe/London',
		],
	},
	{
		value: 'GMT Standard Time',
		abbr: 'GDT',
		offset: 1,
		isdst: true,
		text: '(UTC) Dublin, Lisbon',
		utc: [
			'Atlantic/Canary',
			'Atlantic/Faeroe',
			'Atlantic/Madeira',
			'Europe/Dublin',
			'Europe/Lisbon',
		],
	},
	{
		value: 'Greenwich Standard Time',
		abbr: 'GST',
		offset: 0,
		isdst: false,
		text: '(UTC) Monrovia, Reykjavik',
		utc: [
			'Africa/Abidjan',
			'Africa/Accra',
			'Africa/Bamako',
			'Africa/Banjul',
			'Africa/Bissau',
			'Africa/Conakry',
			'Africa/Dakar',
			'Africa/Freetown',
			'Africa/Lome',
			'Africa/Monrovia',
			'Africa/Nouakchott',
			'Africa/Ouagadougou',
			'Africa/Sao_Tome',
			'Atlantic/Reykjavik',
			'Atlantic/St_Helena',
		],
	},
	{
		value: 'W. Europe Standard Time',
		abbr: 'WEDT',
		offset: 2,
		isdst: true,
		text: '(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna',
		utc: [
			'Arctic/Longyearbyen',
			'Europe/Amsterdam',
			'Europe/Andorra',
			'Europe/Berlin',
			'Europe/Busingen',
			'Europe/Gibraltar',
			'Europe/Luxembourg',
			'Europe/Malta',
			'Europe/Monaco',
			'Europe/Oslo',
			'Europe/Rome',
			'Europe/San_Marino',
			'Europe/Stockholm',
			'Europe/Vaduz',
			'Europe/Vatican',
			'Europe/Vienna',
			'Europe/Zurich',
		],
	},
	{
		value: 'Central Europe Standard Time',
		abbr: 'CEDT',
		offset: 2,
		isdst: true,
		text: '(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague',
		utc: [
			'Europe/Belgrade',
			'Europe/Bratislava',
			'Europe/Budapest',
			'Europe/Ljubljana',
			'Europe/Podgorica',
			'Europe/Prague',
			'Europe/Tirane',
		],
	},
	{
		value: 'Romance Standard Time',
		abbr: 'RDT',
		offset: 2,
		isdst: true,
		text: '(UTC+01:00) Brussels, Copenhagen, Madrid, Paris',
		utc: [
			'Africa/Ceuta',
			'Europe/Brussels',
			'Europe/Copenhagen',
			'Europe/Madrid',
			'Europe/Paris',
		],
	},
	{
		value: 'Central European Standard Time',
		abbr: 'CEDT',
		offset: 2,
		isdst: true,
		text: '(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb',
		utc: ['Europe/Sarajevo', 'Europe/Skopje', 'Europe/Warsaw', 'Europe/Zagreb'],
	},
	{
		value: 'W. Central Africa Standard Time',
		abbr: 'WCAST',
		offset: 1,
		isdst: false,
		text: '(UTC+01:00) West Central Africa',
		utc: [
			'Africa/Algiers',
			'Africa/Bangui',
			'Africa/Brazzaville',
			'Africa/Douala',
			'Africa/Kinshasa',
			'Africa/Lagos',
			'Africa/Libreville',
			'Africa/Luanda',
			'Africa/Malabo',
			'Africa/Ndjamena',
			'Africa/Niamey',
			'Africa/Porto-Novo',
			'Africa/Tunis',
			'Etc/GMT-1',
		],
	},
	{
		value: 'Namibia Standard Time',
		abbr: 'NST',
		offset: 1,
		isdst: false,
		text: '(UTC+01:00) Windhoek',
		utc: ['Africa/Windhoek'],
	},
	{
		value: 'GTB Standard Time',
		abbr: 'GDT',
		offset: 3,
		isdst: true,
		text: '(UTC+02:00) Athens, Bucharest',
		utc: [
			'Asia/Nicosia',
			'Europe/Athens',
			'Europe/Bucharest',
			'Europe/Chisinau',
		],
	},
	{
		value: 'Middle East Standard Time',
		abbr: 'MEDT',
		offset: 3,
		isdst: true,
		text: '(UTC+02:00) Beirut',
		utc: ['Asia/Beirut'],
	},
	{
		value: 'Egypt Standard Time',
		abbr: 'EST',
		offset: 2,
		isdst: false,
		text: '(UTC+02:00) Cairo',
		utc: ['Africa/Cairo'],
	},
	{
		value: 'Syria Standard Time',
		abbr: 'SDT',
		offset: 3,
		isdst: true,
		text: '(UTC+02:00) Damascus',
		utc: ['Asia/Damascus'],
	},
	{
		value: 'E. Europe Standard Time',
		abbr: 'EEDT',
		offset: 3,
		isdst: true,
		text: '(UTC+02:00) E. Europe',
		utc: [
			'Asia/Nicosia',
			'Europe/Athens',
			'Europe/Bucharest',
			'Europe/Chisinau',
			'Europe/Helsinki',
			'Europe/Kyiv',
			'Europe/Mariehamn',
			'Europe/Nicosia',
			'Europe/Riga',
			'Europe/Sofia',
			'Europe/Tallinn',
			'Europe/Uzhgorod',
			'Europe/Vilnius',
			'Europe/Zaporozhye',
		],
	},
	{
		value: 'South Africa Standard Time',
		abbr: 'SAST',
		offset: 2,
		isdst: false,
		text: '(UTC+02:00) Harare, Pretoria',
		utc: [
			'Africa/Blantyre',
			'Africa/Bujumbura',
			'Africa/Gaborone',
			'Africa/Harare',
			'Africa/Johannesburg',
			'Africa/Kigali',
			'Africa/Lubumbashi',
			'Africa/Lusaka',
			'Africa/Maputo',
			'Africa/Maseru',
			'Africa/Mbabane',
			'Etc/GMT-2',
		],
	},
	{
		value: 'FLE Standard Time',
		abbr: 'FDT',
		offset: 3,
		isdst: true,
		text: '(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius',
		utc: [
			'Europe/Helsinki',
			'Europe/Kyiv',
			'Europe/Mariehamn',
			'Europe/Riga',
			'Europe/Sofia',
			'Europe/Tallinn',
			'Europe/Uzhgorod',
			'Europe/Vilnius',
			'Europe/Zaporozhye',
		],
	},
	{
		value: 'Turkey Standard Time',
		abbr: 'TDT',
		offset: 3,
		isdst: false,
		text: '(UTC+03:00) Istanbul',
		utc: ['Europe/Istanbul'],
	},
	{
		value: 'Israel Standard Time',
		abbr: 'JDT',
		offset: 3,
		isdst: true,
		text: '(UTC+02:00) Jerusalem',
		utc: ['Asia/Jerusalem'],
	},
	{
		value: 'Libya Standard Time',
		abbr: 'LST',
		offset: 2,
		isdst: false,
		text: '(UTC+02:00) Tripoli',
		utc: ['Africa/Tripoli'],
	},
	{
		value: 'Jordan Standard Time',
		abbr: 'JST',
		offset: 3,
		isdst: false,
		text: '(UTC+03:00) Amman',
		utc: ['Asia/Amman'],
	},
	{
		value: 'Arabic Standard Time',
		abbr: 'AST',
		offset: 3,
		isdst: false,
		text: '(UTC+03:00) Baghdad',
		utc: ['Asia/Baghdad'],
	},
	{
		value: 'Kaliningrad Standard Time',
		abbr: 'KST',
		offset: 3,
		isdst: false,
		text: '(UTC+02:00) Kaliningrad',
		utc: ['Europe/Kaliningrad'],
	},
	{
		value: 'Arab Standard Time',
		abbr: 'AST',
		offset: 3,
		isdst: false,
		text: '(UTC+03:00) Kuwait, Riyadh',
		utc: [
			'Asia/Aden',
			'Asia/Bahrain',
			'Asia/Kuwait',
			'Asia/Qatar',
			'Asia/Riyadh',
		],
	},
	{
		value: 'E. Africa Standard Time',
		abbr: 'EAST',
		offset: 3,
		isdst: false,
		text: '(UTC+03:00) Nairobi',
		utc: [
			'Africa/Addis_Ababa',
			'Africa/Asmera',
			'Africa/Dar_es_Salaam',
			'Africa/Djibouti',
			'Africa/Juba',
			'Africa/Kampala',
			'Africa/Khartoum',
			'Africa/Mogadishu',
			'Africa/Nairobi',
			'Antarctica/Syowa',
			'Etc/GMT-3',
			'Indian/Antananarivo',
			'Indian/Comoro',
			'Indian/Mayotte',
		],
	},
	{
		value: 'Moscow Standard Time',
		abbr: 'MSK',
		offset: 3,
		isdst: false,
		text: '(UTC+03:00) Moscow, St. Petersburg, Volgograd, Minsk',
		utc: [
			'Europe/Kirov',
			'Europe/Moscow',
			'Europe/Simferopol',
			'Europe/Volgograd',
			'Europe/Minsk',
		],
	},
	{
		value: 'Samara Time',
		abbr: 'SAMT',
		offset: 4,
		isdst: false,
		text: '(UTC+04:00) Samara, Ulyanovsk, Saratov',
		utc: ['Europe/Astrakhan', 'Europe/Samara', 'Europe/Ulyanovsk'],
	},
	{
		value: 'Iran Standard Time',
		abbr: 'IDT',
		offset: 4.5,
		isdst: true,
		text: '(UTC+03:30) Tehran',
		utc: ['Asia/Tehran'],
	},
	{
		value: 'Arabian Standard Time',
		abbr: 'AST',
		offset: 4,
		isdst: false,
		text: '(UTC+04:00) Abu Dhabi, Muscat',
		utc: ['Asia/Dubai', 'Asia/Muscat', 'Etc/GMT-4'],
	},
	{
		value: 'Azerbaijan Standard Time',
		abbr: 'ADT',
		offset: 5,
		isdst: true,
		text: '(UTC+04:00) Baku',
		utc: ['Asia/Baku'],
	},
	{
		value: 'Mauritius Standard Time',
		abbr: 'MST',
		offset: 4,
		isdst: false,
		text: '(UTC+04:00) Port Louis',
		utc: ['Indian/Mahe', 'Indian/Mauritius', 'Indian/Reunion'],
	},
	{
		value: 'Georgian Standard Time',
		abbr: 'GET',
		offset: 4,
		isdst: false,
		text: '(UTC+04:00) Tbilisi',
		utc: ['Asia/Tbilisi'],
	},
	{
		value: 'Caucasus Standard Time',
		abbr: 'CST',
		offset: 4,
		isdst: false,
		text: '(UTC+04:00) Yerevan',
		utc: ['Asia/Yerevan'],
	},
	{
		value: 'Afghanistan Standard Time',
		abbr: 'AST',
		offset: 4.5,
		isdst: false,
		text: '(UTC+04:30) Kabul',
		utc: ['Asia/Kabul'],
	},
	{
		value: 'West Asia Standard Time',
		abbr: 'WAST',
		offset: 5,
		isdst: false,
		text: '(UTC+05:00) Ashgabat, Tashkent',
		utc: [
			'Antarctica/Mawson',
			'Asia/Aqtau',
			'Asia/Aqtobe',
			'Asia/Ashgabat',
			'Asia/Dushanbe',
			'Asia/Oral',
			'Asia/Samarkand',
			'Asia/Tashkent',
			'Etc/GMT-5',
			'Indian/Kerguelen',
			'Indian/Maldives',
		],
	},
	{
		value: 'Yekaterinburg Time',
		abbr: 'YEKT',
		offset: 5,
		isdst: false,
		text: '(UTC+05:00) Yekaterinburg',
		utc: ['Asia/Yekaterinburg'],
	},
	{
		value: 'Pakistan Standard Time',
		abbr: 'PKT',
		offset: 5,
		isdst: false,
		text: '(UTC+05:00) Islamabad, Karachi',
		utc: ['Asia/Karachi'],
	},
	{
		value: 'India Standard Time',
		abbr: 'IST',
		offset: 5.5,
		isdst: false,
		text: '(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi',
		utc: ['Asia/Kolkata', 'Asia/Calcutta'],
	},
	{
		value: 'Sri Lanka Standard Time',
		abbr: 'SLST',
		offset: 5.5,
		isdst: false,
		text: '(UTC+05:30) Sri Jayawardenepura',
		utc: ['Asia/Colombo'],
	},
	{
		value: 'Nepal Standard Time',
		abbr: 'NST',
		offset: 5.75,
		isdst: false,
		text: '(UTC+05:45) Kathmandu',
		utc: ['Asia/Kathmandu'],
	},
	{
		value: 'Central Asia Standard Time',
		abbr: 'CAST',
		offset: 6,
		isdst: false,
		text: '(UTC+06:00) Nur-Sultan (Astana)',
		utc: [
			'Antarctica/Vostok',
			'Asia/Almaty',
			'Asia/Bishkek',
			'Asia/Qyzylorda',
			'Asia/Urumqi',
			'Etc/GMT-6',
			'Indian/Chagos',
		],
	},
	{
		value: 'Bangladesh Standard Time',
		abbr: 'BST',
		offset: 6,
		isdst: false,
		text: '(UTC+06:00) Dhaka',
		utc: ['Asia/Dhaka', 'Asia/Thimphu'],
	},
	{
		value: 'Myanmar Standard Time',
		abbr: 'MST',
		offset: 6.5,
		isdst: false,
		text: '(UTC+06:30) Yangon (Rangoon)',
		utc: ['Asia/Rangoon', 'Indian/Cocos'],
	},
	{
		value: 'SE Asia Standard Time',
		abbr: 'SAST',
		offset: 7,
		isdst: false,
		text: '(UTC+07:00) Bangkok, Hanoi, Jakarta',
		utc: [
			'Antarctica/Davis',
			'Asia/Bangkok',
			'Asia/Hovd',
			'Asia/Jakarta',
			'Asia/Phnom_Penh',
			'Asia/Pontianak',
			'Asia/Saigon',
			'Asia/Vientiane',
			'Etc/GMT-7',
			'Indian/Christmas',
		],
	},
	{
		value: 'N. Central Asia Standard Time',
		abbr: 'NCAST',
		offset: 7,
		isdst: false,
		text: '(UTC+07:00) Novosibirsk',
		utc: ['Asia/Novokuznetsk', 'Asia/Novosibirsk', 'Asia/Omsk'],
	},
	{
		value: 'China Standard Time',
		abbr: 'CST',
		offset: 8,
		isdst: false,
		text: '(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi',
		utc: ['Asia/Hong_Kong', 'Asia/Macau', 'Asia/Shanghai'],
	},
	{
		value: 'North Asia Standard Time',
		abbr: 'NAST',
		offset: 8,
		isdst: false,
		text: '(UTC+08:00) Krasnoyarsk',
		utc: ['Asia/Krasnoyarsk'],
	},
	{
		value: 'Singapore Standard Time',
		abbr: 'MPST',
		offset: 8,
		isdst: false,
		text: '(UTC+08:00) Kuala Lumpur, Singapore',
		utc: [
			'Asia/Brunei',
			'Asia/Kuala_Lumpur',
			'Asia/Kuching',
			'Asia/Makassar',
			'Asia/Manila',
			'Asia/Singapore',
			'Etc/GMT-8',
		],
	},
	{
		value: 'W. Australia Standard Time',
		abbr: 'WAST',
		offset: 8,
		isdst: false,
		text: '(UTC+08:00) Perth',
		utc: ['Antarctica/Casey', 'Australia/Perth'],
	},
	{
		value: 'Taipei Standard Time',
		abbr: 'TST',
		offset: 8,
		isdst: false,
		text: '(UTC+08:00) Taipei',
		utc: ['Asia/Taipei'],
	},
	{
		value: 'Ulaanbaatar Standard Time',
		abbr: 'UST',
		offset: 8,
		isdst: false,
		text: '(UTC+08:00) Ulaanbaatar',
		utc: ['Asia/Choibalsan', 'Asia/Ulaanbaatar'],
	},
	{
		value: 'North Asia East Standard Time',
		abbr: 'NAEST',
		offset: 8,
		isdst: false,
		text: '(UTC+08:00) Irkutsk',
		utc: ['Asia/Irkutsk'],
	},
	{
		value: 'Japan Standard Time',
		abbr: 'JST',
		offset: 9,
		isdst: false,
		text: '(UTC+09:00) Osaka, Sapporo, Tokyo',
		utc: [
			'Asia/Dili',
			'Asia/Jayapura',
			'Asia/Tokyo',
			'Etc/GMT-9',
			'Pacific/Palau',
		],
	},
	{
		value: 'Korea Standard Time',
		abbr: 'KST',
		offset: 9,
		isdst: false,
		text: '(UTC+09:00) Seoul',
		utc: ['Asia/Pyongyang', 'Asia/Seoul'],
	},
	{
		value: 'Cen. Australia Standard Time',
		abbr: 'CAST',
		offset: 9.5,
		isdst: false,
		text: '(UTC+09:30) Adelaide',
		utc: ['Australia/Adelaide', 'Australia/Broken_Hill'],
	},
	{
		value: 'AUS Central Standard Time',
		abbr: 'ACST',
		offset: 9.5,
		isdst: false,
		text: '(UTC+09:30) Darwin',
		utc: ['Australia/Darwin'],
	},
	{
		value: 'E. Australia Standard Time',
		abbr: 'EAST',
		offset: 10,
		isdst: false,
		text: '(UTC+10:00) Brisbane',
		utc: ['Australia/Brisbane', 'Australia/Lindeman'],
	},
	{
		value: 'AUS Eastern Standard Time',
		abbr: 'AEST',
		offset: 10,
		isdst: false,
		text: '(UTC+10:00) Canberra, Melbourne, Sydney',
		utc: ['Australia/Melbourne', 'Australia/Sydney'],
	},
	{
		value: 'West Pacific Standard Time',
		abbr: 'WPST',
		offset: 10,
		isdst: false,
		text: '(UTC+10:00) Guam, Port Moresby',
		utc: [
			'Antarctica/DumontDUrville',
			'Etc/GMT-10',
			'Pacific/Guam',
			'Pacific/Port_Moresby',
			'Pacific/Saipan',
			'Pacific/Truk',
		],
	},
	{
		value: 'Tasmania Standard Time',
		abbr: 'TST',
		offset: 10,
		isdst: false,
		text: '(UTC+10:00) Hobart',
		utc: ['Australia/Currie', 'Australia/Hobart'],
	},
	{
		value: 'Yakutsk Standard Time',
		abbr: 'YST',
		offset: 9,
		isdst: false,
		text: '(UTC+09:00) Yakutsk',
		utc: ['Asia/Chita', 'Asia/Khandyga', 'Asia/Yakutsk'],
	},
	{
		value: 'Central Pacific Standard Time',
		abbr: 'CPST',
		offset: 11,
		isdst: false,
		text: '(UTC+11:00) Solomon Is., New Caledonia',
		utc: [
			'Antarctica/Macquarie',
			'Etc/GMT-11',
			'Pacific/Efate',
			'Pacific/Guadalcanal',
			'Pacific/Kosrae',
			'Pacific/Noumea',
			'Pacific/Ponape',
		],
	},
	{
		value: 'Vladivostok Standard Time',
		abbr: 'VST',
		offset: 11,
		isdst: false,
		text: '(UTC+11:00) Vladivostok',
		utc: ['Asia/Sakhalin', 'Asia/Ust-Nera', 'Asia/Vladivostok'],
	},
	{
		value: 'New Zealand Standard Time',
		abbr: 'NZST',
		offset: 12,
		isdst: false,
		text: '(UTC+12:00) Auckland, Wellington',
		utc: ['Antarctica/McMurdo', 'Pacific/Auckland'],
	},
	{
		value: 'UTC+12',
		abbr: 'U',
		offset: 12,
		isdst: false,
		text: '(UTC+12:00) Coordinated Universal Time+12',
		utc: [
			'Etc/GMT-12',
			'Pacific/Funafuti',
			'Pacific/Kwajalein',
			'Pacific/Majuro',
			'Pacific/Nauru',
			'Pacific/Tarawa',
			'Pacific/Wake',
			'Pacific/Wallis',
		],
	},
	{
		value: 'Fiji Standard Time',
		abbr: 'FST',
		offset: 12,
		isdst: false,
		text: '(UTC+12:00) Fiji',
		utc: ['Pacific/Fiji'],
	},
	{
		value: 'Magadan Standard Time',
		abbr: 'MST',
		offset: 12,
		isdst: false,
		text: '(UTC+12:00) Magadan',
		utc: [
			'Asia/Anadyr',
			'Asia/Kamchatka',
			'Asia/Magadan',
			'Asia/Srednekolymsk',
		],
	},
	{
		value: 'Kamchatka Standard Time',
		abbr: 'KDT',
		offset: 13,
		isdst: true,
		text: '(UTC+12:00) Petropavlovsk-Kamchatsky - Old',
		utc: ['Asia/Kamchatka'],
	},
	{
		value: 'Tonga Standard Time',
		abbr: 'TST',
		offset: 13,
		isdst: false,
		text: "(UTC+13:00) Nuku'alofa",
		utc: [
			'Etc/GMT-13',
			'Pacific/Enderbury',
			'Pacific/Fakaofo',
			'Pacific/Tongatapu',
		],
	},
	{
		value: 'Samoa Standard Time',
		abbr: 'SST',
		offset: 13,
		isdst: false,
		text: '(UTC+13:00) Samoa',
		utc: ['Pacific/Apia'],
	},
] as const;

/**
 * Picklist of timezones.
 * @description The type of the timezone picklist.
 * @type {TimezonePicklist[]}
 * @readonly
 * @version 0.0.1
 * @example
 * e.g.
 * `{ value: 'Dateline Standard Time', abbr: 'DST', offset: -12 }`
 * `{ value: 'UTC-11', abbr: 'U', offset: -11 }`
 * `{ value: 'Hawaiian Standard Time', abbr: 'HST', offset: -10 }`
 */
export const tzPicklist: TimezonePicklist[] = [
	{
		value: 'Dateline Standard Time',
		abbr: 'DST',
		offset: -12,
	},
	{
		value: 'UTC-11',
		abbr: 'U',
		offset: -11,
	},
	{
		value: 'Hawaiian Standard Time',
		abbr: 'HST',
		offset: -10,
	},
	{
		value: 'Alaskan Standard Time',
		abbr: 'AKDT',
		offset: -8,
	},
	{
		value: 'Pacific Standard Time (Mexico)',
		abbr: 'PDT',
		offset: -7,
	},
	{
		value: 'Pacific Daylight Time',
		abbr: 'PDT',
		offset: -7,
	},
	{
		value: 'Pacific Standard Time',
		abbr: 'PST',
		offset: -8,
	},
	{
		value: 'US Mountain Standard Time',
		abbr: 'UMST',
		offset: -7,
	},
	{
		value: 'Mountain Standard Time (Mexico)',
		abbr: 'MDT',
		offset: -6,
	},
	{
		value: 'Mountain Standard Time',
		abbr: 'MDT',
		offset: -6,
	},
	{
		value: 'Central America Standard Time',
		abbr: 'CAST',
		offset: -6,
	},
	{
		value: 'Central Standard Time',
		abbr: 'CDT',
		offset: -5,
	},
	{
		value: 'Central Standard Time (Mexico)',
		abbr: 'CDT',
		offset: -5,
	},
	{
		value: 'Canada Central Standard Time',
		abbr: 'CCST',
		offset: -6,
	},
	{
		value: 'SA Pacific Standard Time',
		abbr: 'SPST',
		offset: -5,
	},
	{
		value: 'Eastern Standard Time',
		abbr: 'EST',
		offset: -5,
	},
	{
		value: 'Eastern Daylight Time',
		abbr: 'EDT',
		offset: -4,
	},
	{
		value: 'US Eastern Standard Time',
		abbr: 'UEDT',
		offset: -5,
	},
	{
		value: 'Venezuela Standard Time',
		abbr: 'VST',
		offset: -4.5,
	},
	{
		value: 'Paraguay Standard Time',
		abbr: 'PYT',
		offset: -4,
	},
	{
		value: 'Atlantic Standard Time',
		abbr: 'ADT',
		offset: -3,
	},
	{
		value: 'Central Brazilian Standard Time',
		abbr: 'CBST',
		offset: -4,
	},
	{
		value: 'SA Western Standard Time',
		abbr: 'SWST',
		offset: -4,
	},
	{
		value: 'Pacific SA Standard Time',
		abbr: 'PSST',
		offset: -4,
	},
	{
		value: 'Newfoundland Standard Time',
		abbr: 'NDT',
		offset: -2.5,
	},
	{
		value: 'E. South America Standard Time',
		abbr: 'ESAST',
		offset: -3,
	},
	{
		value: 'Argentina Standard Time',
		abbr: 'AST',
		offset: -3,
	},
	{
		value: 'SA Eastern Standard Time',
		abbr: 'SEST',
		offset: -3,
	},
	{
		value: 'Greenland Standard Time',
		abbr: 'GDT',
		offset: -3,
	},
	{
		value: 'Montevideo Standard Time',
		abbr: 'MST',
		offset: -3,
	},
	{
		value: 'Bahia Standard Time',
		abbr: 'BST',
		offset: -3,
	},
	{
		value: 'UTC-02',
		abbr: 'U',
		offset: -2,
	},
	{
		value: 'Mid-Atlantic Standard Time',
		abbr: 'MDT',
		offset: -1,
	},
	{
		value: 'Azores Standard Time',
		abbr: 'ADT',
		offset: 0,
	},
	{
		value: 'Cape Verde Standard Time',
		abbr: 'CVST',
		offset: -1,
	},
	{
		value: 'Morocco Standard Time',
		abbr: 'MDT',
		offset: 1,
	},
	{
		value: 'UTC',
		abbr: 'UTC',
		offset: 0,
	},
	{
		value: 'GMT Standard Time',
		abbr: 'GMT',
		offset: 0,
	},
	{
		value: 'British Summer Time',
		abbr: 'BST',
		offset: 1,
	},
	{
		value: 'GMT Standard Time',
		abbr: 'GDT',
		offset: 1,
	},
	{
		value: 'Greenwich Standard Time',
		abbr: 'GST',
		offset: 0,
	},
	{
		value: 'W. Europe Standard Time',
		abbr: 'WEDT',
		offset: 2,
	},
	{
		value: 'Central Europe Standard Time',
		abbr: 'CEDT',
		offset: 2,
	},
	{
		value: 'Romance Standard Time',
		abbr: 'RDT',
		offset: 2,
	},
	{
		value: 'Central European Standard Time',
		abbr: 'CEDT',
		offset: 2,
	},
	{
		value: 'W. Central Africa Standard Time',
		abbr: 'WCAST',
		offset: 1,
	},
	{
		value: 'Namibia Standard Time',
		abbr: 'NST',
		offset: 1,
	},
	{
		value: 'GTB Standard Time',
		abbr: 'GDT',
		offset: 3,
	},
	{
		value: 'Middle East Standard Time',
		abbr: 'MEDT',
		offset: 3,
	},
	{
		value: 'Egypt Standard Time',
		abbr: 'EST',
		offset: 2,
	},
	{
		value: 'Syria Standard Time',
		abbr: 'SDT',
		offset: 3,
	},
	{
		value: 'E. Europe Standard Time',
		abbr: 'EEDT',
		offset: 3,
	},
	{
		value: 'South Africa Standard Time',
		abbr: 'SAST',
		offset: 2,
	},
	{
		value: 'FLE Standard Time',
		abbr: 'FDT',
		offset: 3,
	},
	{
		value: 'Turkey Standard Time',
		abbr: 'TDT',
		offset: 3,
	},
	{
		value: 'Israel Standard Time',
		abbr: 'JDT',
		offset: 3,
	},
	{
		value: 'Libya Standard Time',
		abbr: 'LST',
		offset: 2,
	},
	{
		value: 'Jordan Standard Time',
		abbr: 'JST',
		offset: 3,
	},
	{
		value: 'Arabic Standard Time',
		abbr: 'AST',
		offset: 3,
	},
	{
		value: 'Kaliningrad Standard Time',
		abbr: 'KST',
		offset: 3,
	},
	{
		value: 'Arab Standard Time',
		abbr: 'AST',
		offset: 3,
	},
	{
		value: 'E. Africa Standard Time',
		abbr: 'EAST',
		offset: 3,
	},
	{
		value: 'Moscow Standard Time',
		abbr: 'MSK',
		offset: 3,
	},
	{
		value: 'Samara Time',
		abbr: 'SAMT',
		offset: 4,
	},
	{
		value: 'Iran Standard Time',
		abbr: 'IDT',
		offset: 4.5,
	},
	{
		value: 'Arabian Standard Time',
		abbr: 'AST',
		offset: 4,
	},
	{
		value: 'Azerbaijan Standard Time',
		abbr: 'ADT',
		offset: 5,
	},
	{
		value: 'Mauritius Standard Time',
		abbr: 'MST',
		offset: 4,
	},
	{
		value: 'Georgian Standard Time',
		abbr: 'GET',
		offset: 4,
	},
	{
		value: 'Caucasus Standard Time',
		abbr: 'CST',
		offset: 4,
	},
	{
		value: 'Afghanistan Standard Time',
		abbr: 'AST',
		offset: 4.5,
	},
	{
		value: 'West Asia Standard Time',
		abbr: 'WAST',
		offset: 5,
	},
	{
		value: 'Yekaterinburg Time',
		abbr: 'YEKT',
		offset: 5,
	},
	{
		value: 'Pakistan Standard Time',
		abbr: 'PKT',
		offset: 5,
	},
	{
		value: 'India Standard Time',
		abbr: 'IST',
		offset: 5.5,
	},
	{
		value: 'Sri Lanka Standard Time',
		abbr: 'SLST',
		offset: 5.5,
	},
	{
		value: 'Nepal Standard Time',
		abbr: 'NST',
		offset: 5.75,
	},
	{
		value: 'Central Asia Standard Time',
		abbr: 'CAST',
		offset: 6,
	},
	{
		value: 'Bangladesh Standard Time',
		abbr: 'BST',
		offset: 6,
	},
	{
		value: 'Myanmar Standard Time',
		abbr: 'MST',
		offset: 6.5,
	},
	{
		value: 'SE Asia Standard Time',
		abbr: 'SAST',
		offset: 7,
	},
	{
		value: 'N. Central Asia Standard Time',
		abbr: 'NCAST',
		offset: 7,
	},
	{
		value: 'China Standard Time',
		abbr: 'CST',
		offset: 8,
	},
	{
		value: 'North Asia Standard Time',
		abbr: 'NAST',
		offset: 8,
	},
	{
		value: 'Singapore Standard Time',
		abbr: 'MPST',
		offset: 8,
	},
	{
		value: 'W. Australia Standard Time',
		abbr: 'WAST',
		offset: 8,
	},
	{
		value: 'Taipei Standard Time',
		abbr: 'TST',
		offset: 8,
	},
	{
		value: 'Ulaanbaatar Standard Time',
		abbr: 'UST',
		offset: 8,
	},
	{
		value: 'North Asia East Standard Time',
		abbr: 'NAEST',
		offset: 8,
	},
	{
		value: 'Japan Standard Time',
		abbr: 'JST',
		offset: 9,
	},
	{
		value: 'Korea Standard Time',
		abbr: 'KST',
		offset: 9,
	},
	{
		value: 'Cen. Australia Standard Time',
		abbr: 'CAST',
		offset: 9.5,
	},
	{
		value: 'AUS Central Standard Time',
		abbr: 'ACST',
		offset: 9.5,
	},
	{
		value: 'E. Australia Standard Time',
		abbr: 'EAST',
		offset: 10,
	},
	{
		value: 'AUS Eastern Standard Time',
		abbr: 'AEST',
		offset: 10,
	},
	{
		value: 'West Pacific Standard Time',
		abbr: 'WPST',
		offset: 10,
	},
	{
		value: 'Tasmania Standard Time',
		abbr: 'TST',
		offset: 10,
	},
	{
		value: 'Yakutsk Standard Time',
		abbr: 'YST',
		offset: 9,
	},
	{
		value: 'Central Pacific Standard Time',
		abbr: 'CPST',
		offset: 11,
	},
	{
		value: 'Vladivostok Standard Time',
		abbr: 'VST',
		offset: 11,
	},
	{
		value: 'New Zealand Standard Time',
		abbr: 'NZST',
		offset: 12,
	},
	{
		value: 'UTC+12',
		abbr: 'U',
		offset: 12,
	},
	{
		value: 'Fiji Standard Time',
		abbr: 'FST',
		offset: 12,
	},
	{
		value: 'Magadan Standard Time',
		abbr: 'MST',
		offset: 12,
	},
	{
		value: 'Kamchatka Standard Time',
		abbr: 'KDT',
		offset: 13,
	},
	{
		value: 'Tonga Standard Time',
		abbr: 'TST',
		offset: 13,
	},
	{
		value: 'Samoa Standard Time',
		abbr: 'SST',
		offset: 13,
	},
];
/**
 * Timezone Enum
 * @type {TimezonePicklist}
 * @readonly
 * @version 0.0.1
 * @example
 * e.g.
 * `Timezone.DST`
 * `Timezone.PST`
 */
export enum TimezoneObj {
	DST = 'DST',
	UTC_11 = 'U',
	HST = 'HST',
	AKDT = 'AKDT',
	PDT = 'PDT',
	PST = 'PST',
	UMST = 'UMST',
	MDT = 'MDT',
	CAST = 'CAST',
	CDT = 'CDT',
	CCST = 'CCST',
	SPST = 'SPST',
	EST = 'EST',
	EDT = 'EDT',
	UEDT = 'UEDT',
	VST = 'VST',
	PYT = 'PYT',
	ADT = 'ADT',
	CBST = 'CBST',
	SWST = 'SWST',
	PSST = 'PSST',
	NDT = 'NDT',
	ESAST = 'ESAST',
	AST = 'AST',
	SEST = 'SEST',
	GDT = 'GDT',
	MST = 'MST',
	BST = 'BST',
	UTC_02 = 'UTC_02',
	CVST = 'CVST',
	UTC = 'UTC',
	GMT = 'GMT',
	GST = 'GST',
	WEDT = 'WEDT',
	CEDT = 'CEDT',
	RDT = 'RDT',
	WCAST = 'WCAST',
	NST = 'NST',
	MEDT = 'MEDT',
	SDT = 'SDT',
	EEDT = 'EEDT',
	SAST = 'SAST',
	FDT = 'FDT',
	TDT = 'TDT',
	JDT = 'JDT',
	LST = 'LST',
	JST = 'JST',
	KST = 'KST',
	EAST = 'EAST',
	MSK = 'MSK',
	SAMT = 'SAMT',
	IDT = 'IDT',
	GET = 'GET',
	CST = 'CST',
	WAST = 'WAST',
	YEKT = 'YEKT',
	PKT = 'PKT',
	IST = 'IST',
	SLST = 'SLST',
	NCAST = 'NCAST',
	NAST = 'NAST',
	MPST = 'MPST',
	UST = 'UST',
	NAEST = 'NAEST',
	ACST = 'ACST',
	AEST = 'AEST',
	WPST = 'WPST',
	YST = 'YST',
	CPST = 'CPST',
	NZST = 'NZST',
	UTC_12 = 'UTC_12',
	FST = 'FST',
	KDT = 'KDT',
	TST = 'TST',
	SST = 'SST',
}

export const TimezoneArray = [
	'DST',
	'UTC-11',
	'U',
	'HST',
	'AKDT',
	'PDT',
	'PDT',
	'PST',
	'UMST',
	'MDT',
	'MDT',
	'CAST',
	'CDT',
	'CDT',
	'CCST',
	'SPST',
	'EST',
	'EDT',
	'UEDT',
	'VST',
	'PYT',
	'ADT',
	'CBST',
	'SWST',
	'PSST',
	'NDT',
	'ESAST',
	'AST',
	'SEST',
	'GDT',
	'MST',
	'BST',
	'UTC-02',
	'U',
	'MDT',
	'ADT',
	'CVST',
	'MDT',
	'UTC',
	'UTC',
	'GMT',
	'BST',
	'GDT',
	'GST',
	'WEDT',
	'CEDT',
	'RDT',
	'CEDT',
	'WCAST',
	'NST',
	'GDT',
	'MEDT',
	'EST',
	'SDT',
	'EEDT',
	'SAST',
	'FDT',
	'TDT',
	'JDT',
	'LST',
	'JST',
	'AST',
	'KST',
	'AST',
	'EAST',
	'MSK',
	'SAMT',
	'IDT',
	'AST',
	'ADT',
	'MST',
	'GET',
	'CST',
	'AST',
	'WAST',
	'YEKT',
	'PKT',
	'IST',
	'SLST',
	'NST',
	'CAST',
	'BST',
	'MST',
	'SAST',
	'NCAST',
	'CST',
	'NAST',
	'MPST',
	'WAST',
	'TST',
	'UST',
	'NAEST',
	'JST',
	'KST',
	'CAST',
	'ACST',
	'EAST',
	'AEST',
	'WPST',
	'TST',
	'YST',
	'CPST',
	'VST',
	'NZST',
	'UTC+12',
	'U',
	'FST',
	'MST',
	'KDT',
	'TST',
	'SST',
] as const;

export enum TimezonePicklistEnum {
	'Africa/Algiers' = 'Africa/Algiers',
	'Atlantic/Cape_Verde' = 'Atlantic/Cape_Verde',
	'Africa/Ndjamena' = 'Africa/Ndjamena',
	'Africa/Abidjan' = 'Africa/Abidjan',
	'Africa/Bamako' = 'Africa/Bamako',
	'Africa/Banjul' = 'Africa/Banjul',
	'Africa/Conakry' = 'Africa/Conakry',
	'Africa/Dakar' = 'Africa/Dakar',
	'Africa/Freetown' = 'Africa/Freetown',
	'Africa/Lome' = 'Africa/Lome',
	'Africa/Nouakchott' = 'Africa/Nouakchott',
	'Africa/Ouagadougou' = 'Africa/Ouagadougou',
	'Atlantic/St_Helena' = 'Atlantic/St_Helena',
	'Africa/Cairo' = 'Africa/Cairo',
	'Africa/Accra' = 'Africa/Accra',
	'Africa/Bissau' = 'Africa/Bissau',
	'Africa/Nairobi' = 'Africa/Nairobi',
	'Africa/Addis_Ababa' = 'Africa/Addis_Ababa',
	'Africa/Asmara' = 'Africa/Asmara',
	'Africa/Dar_es_Salaam' = 'Africa/Dar_es_Salaam',
	'Africa/Djibouti' = 'Africa/Djibouti',
	'Africa/Kampala' = 'Africa/Kampala',
	'Africa/Mogadishu' = 'Africa/Mogadishu',
	'Indian/Antananarivo' = 'Indian/Antananarivo',
	'Indian/Comoro' = 'Indian/Comoro',
	'Indian/Mayotte' = 'Indian/Mayotte',
	'Africa/Monrovia' = 'Africa/Monrovia',
	'Africa/Tripoli' = 'Africa/Tripoli',
	'Indian/Mauritius' = 'Indian/Mauritius',
	'Africa/Casablanca' = 'Africa/Casablanca',
	'Africa/El_Aaiun' = 'Africa/El_Aaiun',
	'Africa/Maputo' = 'Africa/Maputo',
	'Africa/Blantyre' = 'Africa/Blantyre',
	'Africa/Bujumbura' = 'Africa/Bujumbura',
	'Africa/Gaborone' = 'Africa/Gaborone',
	'Africa/Harare' = 'Africa/Harare',
	'Africa/Kigali' = 'Africa/Kigali',
	'Africa/Lubumbashi' = 'Africa/Lubumbashi',
	'Africa/Lusaka' = 'Africa/Lusaka',
	'Africa/Windhoek' = 'Africa/Windhoek',
	'Africa/Lagos' = 'Africa/Lagos',
	'Africa/Bangui' = 'Africa/Bangui',
	'Africa/Brazzaville' = 'Africa/Brazzaville',
	'Africa/Douala' = 'Africa/Douala',
	'Africa/Kinshasa' = 'Africa/Kinshasa',
	'Africa/Libreville' = 'Africa/Libreville',
	'Africa/Luanda' = 'Africa/Luanda',
	'Africa/Malabo' = 'Africa/Malabo',
	'Africa/Niamey' = 'Africa/Niamey',
	'Africa/Porto-Novo' = 'Africa/Porto-Novo',
	'Indian/Reunion' = 'Indian/Reunion',
	'Africa/Sao_Tome' = 'Africa/Sao_Tome',
	'Indian/Mahe' = 'Indian/Mahe',
	'Africa/Johannesburg' = 'Africa/Johannesburg',
	'Africa/Maseru' = 'Africa/Maseru',
	'Africa/Mbabane' = 'Africa/Mbabane',
	'Africa/Khartoum' = 'Africa/Khartoum',
	'Africa/Juba' = 'Africa/Juba',
	'Africa/Tunis' = 'Africa/Tunis',
	'Antarctica/Casey' = 'Antarctica/Casey',
	'Antarctica/Davis' = 'Antarctica/Davis',
	'Antarctica/Mawson' = 'Antarctica/Mawson',
	'Indian/Kerguelen' = 'Indian/Kerguelen',
	'Antarctica/DumontDUrville' = 'Antarctica/DumontDUrville',
	'Antarctica/Syowa' = 'Antarctica/Syowa',
	'Antarctica/Troll' = 'Antarctica/Troll',
	'Antarctica/Vostok' = 'Antarctica/Vostok',
	'Antarctica/Rothera' = 'Antarctica/Rothera',
	'Asia/Kabul' = 'Asia/Kabul',
	'Asia/Yerevan' = 'Asia/Yerevan',
	'Asia/Baku' = 'Asia/Baku',
	'Asia/Dhaka' = 'Asia/Dhaka',
	'Asia/Thimphu' = 'Asia/Thimphu',
	'Indian/Chagos' = 'Indian/Chagos',
	'Asia/Brunei' = 'Asia/Brunei',
	'Asia/Yangon' = 'Asia/Yangon',
	'Asia/Shanghai' = 'Asia/Shanghai',
	'Asia/Urumqi' = 'Asia/Urumqi',
	'Asia/Hong_Kong' = 'Asia/Hong_Kong',
	'Asia/Taipei' = 'Asia/Taipei',
	'Asia/Macau' = 'Asia/Macau',
	'Asia/Nicosia' = 'Asia/Nicosia',
	'Asia/Famagusta' = 'Asia/Famagusta',
	'Europe/Nicosia' = 'Europe/Nicosia',
	'Asia/Tbilisi' = 'Asia/Tbilisi',
	'Asia/Dili' = 'Asia/Dili',
	'Asia/Kolkata' = 'Asia/Kolkata',
	'Asia/Jakarta' = 'Asia/Jakarta',
	'Asia/Pontianak' = 'Asia/Pontianak',
	'Asia/Makassar' = 'Asia/Makassar',
	'Asia/Jayapura' = 'Asia/Jayapura',
	'Asia/Tehran' = 'Asia/Tehran',
	'Asia/Baghdad' = 'Asia/Baghdad',
	'Asia/Jerusalem' = 'Asia/Jerusalem',
	'Asia/Tokyo' = 'Asia/Tokyo',
	'Asia/Amman' = 'Asia/Amman',
	'Asia/Almaty' = 'Asia/Almaty',
	'Asia/Qyzylorda' = 'Asia/Qyzylorda',
	'Asia/Qostanay' = 'Asia/Qostanay',
	'Asia/Aqtobe' = 'Asia/Aqtobe',
	'Asia/Aqtau' = 'Asia/Aqtau',
	'Asia/Atyrau' = 'Asia/Atyrau',
	'Asia/Oral' = 'Asia/Oral',
	'Asia/Bishkek' = 'Asia/Bishkek',
	'Asia/Seoul' = 'Asia/Seoul',
	'Asia/Pyongyang' = 'Asia/Pyongyang',
	'Asia/Beirut' = 'Asia/Beirut',
	'Asia/Kuala_Lumpur' = 'Asia/Kuala_Lumpur',
	'Asia/Kuching' = 'Asia/Kuching',
	'Indian/Maldives' = 'Indian/Maldives',
	'Asia/Hovd' = 'Asia/Hovd',
	'Asia/Ulaanbaatar' = 'Asia/Ulaanbaatar',
	'Asia/Choibalsan' = 'Asia/Choibalsan',
	'Asia/Kathmandu' = 'Asia/Kathmandu',
	'Asia/Karachi' = 'Asia/Karachi',
	'Asia/Gaza' = 'Asia/Gaza',
	'Asia/Hebron' = 'Asia/Hebron',
	'Asia/Manila' = 'Asia/Manila',
	'Asia/Qatar' = 'Asia/Qatar',
	'Asia/Bahrain' = 'Asia/Bahrain',
	'Asia/Riyadh' = 'Asia/Riyadh',
	'Asia/Aden' = 'Asia/Aden',
	'Asia/Kuwait' = 'Asia/Kuwait',
	'Asia/Singapore' = 'Asia/Singapore',
	'Asia/Colombo' = 'Asia/Colombo',
	'Asia/Damascus' = 'Asia/Damascus',
	'Asia/Dushanbe' = 'Asia/Dushanbe',
	'Asia/Bangkok' = 'Asia/Bangkok',
	'Asia/Phnom_Penh' = 'Asia/Phnom_Penh',
	'Asia/Vientiane' = 'Asia/Vientiane',
	'Asia/Ashgabat' = 'Asia/Ashgabat',
	'Asia/Dubai' = 'Asia/Dubai',
	'Asia/Muscat' = 'Asia/Muscat',
	'Asia/Samarkand' = 'Asia/Samarkand',
	'Asia/Tashkent' = 'Asia/Tashkent',
	'Asia/Ho_Chi_Minh' = 'Asia/Ho_Chi_Minh',
	'Australia/Darwin' = 'Australia/Darwin',
	'Australia/Perth' = 'Australia/Perth',
	'Australia/Eucla' = 'Australia/Eucla',
	'Australia/Brisbane' = 'Australia/Brisbane',
	'Australia/Lindeman' = 'Australia/Lindeman',
	'Australia/Adelaide' = 'Australia/Adelaide',
	'Australia/Hobart' = 'Australia/Hobart',
	'Australia/Currie' = 'Australia/Currie',
	'Australia/Melbourne' = 'Australia/Melbourne',
	'Australia/Sydney' = 'Australia/Sydney',
	'Australia/Broken_Hill' = 'Australia/Broken_Hill',
	'Australia/Lord_Howe' = 'Australia/Lord_Howe',
	'Antarctica/Macquarie' = 'Antarctica/Macquarie',
	'Indian/Christmas' = 'Indian/Christmas',
	'Indian/Cocos' = 'Indian/Cocos',
	'Pacific/Fiji' = 'Pacific/Fiji',
	'Pacific/Gambier' = 'Pacific/Gambier',
	'Pacific/Marquesas' = 'Pacific/Marquesas',
	'Pacific/Tahiti' = 'Pacific/Tahiti',
	'Pacific/Guam' = 'Pacific/Guam',
	'Pacific/Saipan' = 'Pacific/Saipan',
	'Pacific/Tarawa' = 'Pacific/Tarawa',
	'Pacific/Enderbury' = 'Pacific/Enderbury',
	'Pacific/Kiritimati' = 'Pacific/Kiritimati',
	'Pacific/Majuro' = 'Pacific/Majuro',
	'Pacific/Kwajalein' = 'Pacific/Kwajalein',
	'Pacific/Chuuk' = 'Pacific/Chuuk',
	'Pacific/Pohnpei' = 'Pacific/Pohnpei',
	'Pacific/Kosrae' = 'Pacific/Kosrae',
	'Pacific/Nauru' = 'Pacific/Nauru',
	'Pacific/Noumea' = 'Pacific/Noumea',
	'Pacific/Auckland' = 'Pacific/Auckland',
	'Pacific/Chatham' = 'Pacific/Chatham',
	'Antarctica/McMurdo' = 'Antarctica/McMurdo',
	'Pacific/Rarotonga' = 'Pacific/Rarotonga',
	'Pacific/Niue' = 'Pacific/Niue',
	'Pacific/Norfolk' = 'Pacific/Norfolk',
	'Pacific/Palau' = 'Pacific/Palau',
	'Pacific/Port_Moresby' = 'Pacific/Port_Moresby',
	'Pacific/Bougainville' = 'Pacific/Bougainville',
	'Pacific/Pitcairn' = 'Pacific/Pitcairn',
	'Pacific/Pago_Pago' = 'Pacific/Pago_Pago',
	'Pacific/Midway' = 'Pacific/Midway',
	'Pacific/Apia' = 'Pacific/Apia',
	'Pacific/Guadalcanal' = 'Pacific/Guadalcanal',
	'Pacific/Fakaofo' = 'Pacific/Fakaofo',
	'Pacific/Tongatapu' = 'Pacific/Tongatapu',
	'Pacific/Funafuti' = 'Pacific/Funafuti',
	'Pacific/Wake' = 'Pacific/Wake',
	'Pacific/Efate' = 'Pacific/Efate',
	'Pacific/Wallis' = 'Pacific/Wallis',
	'Africa/Asmera' = 'Africa/Asmera',
	'Africa/Timbuktu' = 'Africa/Timbuktu',
	'America/Argentina/ComodRivadavia' = 'America/Argentina/ComodRivadavia',
	'America/Atka' = 'America/Atka',
	'America/Buenos_Aires' = 'America/Buenos_Aires',
	'America/Catamarca' = 'America/Catamarca',
	'America/Coral_Harbour' = 'America/Coral_Harbour',
	'America/Cordoba' = 'America/Cordoba',
	'America/Ensenada' = 'America/Ensenada',
	'America/Fort_Wayne' = 'America/Fort_Wayne',
	'America/Indianapolis' = 'America/Indianapolis',
	'America/Jujuy' = 'America/Jujuy',
	'America/Knox_IN' = 'America/Knox_IN',
	'America/Louisville' = 'America/Louisville',
	'America/Mendoza' = 'America/Mendoza',
	'America/Montreal' = 'America/Montreal',
	'America/Porto_Acre' = 'America/Porto_Acre',
	'America/Rosario' = 'America/Rosario',
	'America/Santa_Isabel' = 'America/Santa_Isabel',
	'America/Shiprock' = 'America/Shiprock',
	'America/Virgin' = 'America/Virgin',
	'Antarctica/South_Pole' = 'Antarctica/South_Pole',
	'Asia/Ashkhabad' = 'Asia/Ashkhabad',
	'Asia/Calcutta' = 'Asia/Calcutta',
	'Asia/Chongqing' = 'Asia/Chongqing',
	'Asia/Chungking' = 'Asia/Chungking',
	'Asia/Dacca' = 'Asia/Dacca',
	'Asia/Harbin' = 'Asia/Harbin',
	'Asia/Kashgar' = 'Asia/Kashgar',
	'Asia/Katmandu' = 'Asia/Katmandu',
	'Asia/Macao' = 'Asia/Macao',
	'Asia/Rangoon' = 'Asia/Rangoon',
	'Asia/Saigon' = 'Asia/Saigon',
	'Asia/Tel_Aviv' = 'Asia/Tel_Aviv',
	'Asia/Thimbu' = 'Asia/Thimbu',
	'Asia/Ujung_Pandang' = 'Asia/Ujung_Pandang',
	'Asia/Ulan_Bator' = 'Asia/Ulan_Bator',
	'Atlantic/Faeroe' = 'Atlantic/Faeroe',
	'Atlantic/Jan_Mayen' = 'Atlantic/Jan_Mayen',
	'Australia/ACT' = 'Australia/ACT',
	'Australia/Canberra' = 'Australia/Canberra',
	'Australia/LHI' = 'Australia/LHI',
	'Australia/NSW' = 'Australia/NSW',
	'Australia/North' = 'Australia/North',
	'Australia/Queensland' = 'Australia/Queensland',
	'Australia/South' = 'Australia/South',
	'Australia/Tasmania' = 'Australia/Tasmania',
	'Australia/Victoria' = 'Australia/Victoria',
	'Australia/West' = 'Australia/West',
	'Australia/Yancowinna' = 'Australia/Yancowinna',
	'Brazil/Acre' = 'Brazil/Acre',
	'Brazil/DeNoronha' = 'Brazil/DeNoronha',
	'Brazil/East' = 'Brazil/East',
	'Brazil/West' = 'Brazil/West',
	'Canada/Atlantic' = 'Canada/Atlantic',
	'Canada/Central' = 'Canada/Central',
	'Canada/Eastern' = 'Canada/Eastern',
	'Canada/Mountain' = 'Canada/Mountain',
	'Canada/Newfoundland' = 'Canada/Newfoundland',
	'Canada/Pacific' = 'Canada/Pacific',
	'Canada/Saskatchewan' = 'Canada/Saskatchewan',
	'Canada/Yukon' = 'Canada/Yukon',
	'Chile/Continental' = 'Chile/Continental',
	'Chile/EasterIsland' = 'Chile/EasterIsland',
	Cuba = 'Cuba',
	Egypt = 'Egypt',
	Eire = 'Eire',
	'Etc/UCT' = 'Etc/UCT',
	'Europe/Belfast' = 'Europe/Belfast',
	'Europe/Tiraspol' = 'Europe/Tiraspol',
	GB = 'GB',
	'GB-Eire' = 'GB-Eire',
	'GMT+0' = 'GMT+0',
	'GMT-0' = 'GMT-0',
	GMT0 = 'GMT0',
	Greenwich = 'Greenwich',
	Hongkong = 'Hongkong',
	Iceland = 'Iceland',
	Iran = 'Iran',
	Israel = 'Israel',
	Jamaica = 'Jamaica',
	Japan = 'Japan',
	Kwajalein = 'Kwajalein',
	Libya = 'Libya',
	'Mexico/BajaNorte' = 'Mexico/BajaNorte',
	'Mexico/BajaSur' = 'Mexico/BajaSur',
	'Mexico/General' = 'Mexico/General',
	NZ = 'NZ',
	'NZ-CHAT' = 'NZ-CHAT',
	Navajo = 'Navajo',
	PRC = 'PRC',
	'Pacific/Johnston' = 'Pacific/Johnston',
	'Pacific/Ponape' = 'Pacific/Ponape',
	'Pacific/Samoa' = 'Pacific/Samoa',
	'Pacific/Truk' = 'Pacific/Truk',
	'Pacific/Yap' = 'Pacific/Yap',
	Poland = 'Poland',
	Portugal = 'Portugal',
	ROC = 'ROC',
	ROK = 'ROK',
	Singapore = 'Singapore',
	Turkey = 'Turkey',
	UCT = 'UCT',
	'US/Alaska' = 'US/Alaska',
	'US/Aleutian' = 'US/Aleutian',
	'US/Arizona' = 'US/Arizona',
	'US/Central' = 'US/Central',
	'US/East-Indiana' = 'US/East-Indiana',
	'US/Eastern' = 'US/Eastern',
	'US/Hawaii' = 'US/Hawaii',
	'US/Indiana-Starke' = 'US/Indiana-Starke',
	'US/Michigan' = 'US/Michigan',
	'US/Mountain' = 'US/Mountain',
	'US/Pacific' = 'US/Pacific',
	'US/Samoa' = 'US/Samoa',
	UTC = 'UTC',
	Universal = 'Universal',
	'W-SU' = 'W-SU',
	Zulu = 'Zulu',
	'Etc/GMT' = 'Etc/GMT',
	'Etc/UTC' = 'Etc/UTC',
	GMT = 'GMT',
	'Etc/Universal' = 'Etc/Universal',
	'Etc/Zulu' = 'Etc/Zulu',
	'Etc/Greenwich' = 'Etc/Greenwich',
	'Etc/GMT-0' = 'Etc/GMT-0',
	'Etc/GMT+0' = 'Etc/GMT+0',
	'Etc/GMT0' = 'Etc/GMT0',
	'Etc/GMT-14' = 'Etc/GMT-14',
	'Etc/GMT-13' = 'Etc/GMT-13',
	'Etc/GMT-12' = 'Etc/GMT-12',
	'Etc/GMT-11' = 'Etc/GMT-11',
	'Etc/GMT-10' = 'Etc/GMT-10',
	'Etc/GMT-9' = 'Etc/GMT-9',
	'Etc/GMT-8' = 'Etc/GMT-8',
	'Etc/GMT-7' = 'Etc/GMT-7',
	'Etc/GMT-6' = 'Etc/GMT-6',
	'Etc/GMT-5' = 'Etc/GMT-5',
	'Etc/GMT-4' = 'Etc/GMT-4',
	'Etc/GMT-3' = 'Etc/GMT-3',
	'Etc/GMT-2' = 'Etc/GMT-2',
	'Etc/GMT-1' = 'Etc/GMT-1',
	'Etc/GMT+1' = 'Etc/GMT+1',
	'Etc/GMT+2' = 'Etc/GMT+2',
	'Etc/GMT+3' = 'Etc/GMT+3',
	'Etc/GMT+4' = 'Etc/GMT+4',
	'Etc/GMT+5' = 'Etc/GMT+5',
	'Etc/GMT+6' = 'Etc/GMT+6',
	'Etc/GMT+7' = 'Etc/GMT+7',
	'Etc/GMT+8' = 'Etc/GMT+8',
	'Etc/GMT+9' = 'Etc/GMT+9',
	'Etc/GMT+10' = 'Etc/GMT+10',
	'Etc/GMT+11' = 'Etc/GMT+11',
	'Etc/GMT+12' = 'Etc/GMT+12',
	'Europe/London' = 'Europe/London',
	'Europe/Jersey' = 'Europe/Jersey',
	'Europe/Guernsey' = 'Europe/Guernsey',
	'Europe/Isle_of_Man' = 'Europe/Isle_of_Man',
	'Europe/Dublin' = 'Europe/Dublin',
	WET = 'WET',
	CET = 'CET',
	MET = 'MET',
	EET = 'EET',
	'Europe/Tirane' = 'Europe/Tirane',
	'Europe/Andorra' = 'Europe/Andorra',
	'Europe/Vienna' = 'Europe/Vienna',
	'Europe/Minsk' = 'Europe/Minsk',
	'Europe/Brussels' = 'Europe/Brussels',
	'Europe/Sofia' = 'Europe/Sofia',
	'Europe/Prague' = 'Europe/Prague',
	'Europe/Copenhagen' = 'Europe/Copenhagen',
	'Atlantic/Faroe' = 'Atlantic/Faroe',
	'America/Danmarkshavn' = 'America/Danmarkshavn',
	'America/Scoresbysund' = 'America/Scoresbysund',
	'America/Godthab' = 'America/Godthab',
	'America/Thule' = 'America/Thule',
	'Europe/Tallinn' = 'Europe/Tallinn',
	'Europe/Helsinki' = 'Europe/Helsinki',
	'Europe/Mariehamn' = 'Europe/Mariehamn',
	'Europe/Paris' = 'Europe/Paris',
	'Europe/Berlin' = 'Europe/Berlin',
	'Europe/Busingen' = 'Europe/Busingen',
	'Europe/Gibraltar' = 'Europe/Gibraltar',
	'Europe/Athens' = 'Europe/Athens',
	'Europe/Budapest' = 'Europe/Budapest',
	'Atlantic/Reykjavik' = 'Atlantic/Reykjavik',
	'Europe/Rome' = 'Europe/Rome',
	'Europe/Vatican' = 'Europe/Vatican',
	'Europe/San_Marino' = 'Europe/San_Marino',
	'Europe/Riga' = 'Europe/Riga',
	'Europe/Vaduz' = 'Europe/Vaduz',
	'Europe/Vilnius' = 'Europe/Vilnius',
	'Europe/Luxembourg' = 'Europe/Luxembourg',
	'Europe/Malta' = 'Europe/Malta',
	'Europe/Chisinau' = 'Europe/Chisinau',
	'Europe/Monaco' = 'Europe/Monaco',
	'Europe/Amsterdam' = 'Europe/Amsterdam',
	'Europe/Oslo' = 'Europe/Oslo',
	'Arctic/Longyearbyen' = 'Arctic/Longyearbyen',
	'Europe/Warsaw' = 'Europe/Warsaw',
	'Europe/Lisbon' = 'Europe/Lisbon',
	'Atlantic/Azores' = 'Atlantic/Azores',
	'Atlantic/Madeira' = 'Atlantic/Madeira',
	'Europe/Bucharest' = 'Europe/Bucharest',
	'Europe/Kaliningrad' = 'Europe/Kaliningrad',
	'Europe/Moscow' = 'Europe/Moscow',
	'Europe/Simferopol' = 'Europe/Simferopol',
	'Europe/Astrakhan' = 'Europe/Astrakhan',
	'Europe/Volgograd' = 'Europe/Volgograd',
	'Europe/Saratov' = 'Europe/Saratov',
	'Europe/Kirov' = 'Europe/Kirov',
	'Europe/Samara' = 'Europe/Samara',
	'Europe/Ulyanovsk' = 'Europe/Ulyanovsk',
	'Asia/Yekaterinburg' = 'Asia/Yekaterinburg',
	'Asia/Omsk' = 'Asia/Omsk',
	'Asia/Barnaul' = 'Asia/Barnaul',
	'Asia/Novosibirsk' = 'Asia/Novosibirsk',
	'Asia/Tomsk' = 'Asia/Tomsk',
	'Asia/Novokuznetsk' = 'Asia/Novokuznetsk',
	'Asia/Krasnoyarsk' = 'Asia/Krasnoyarsk',
	'Asia/Irkutsk' = 'Asia/Irkutsk',
	'Asia/Chita' = 'Asia/Chita',
	'Asia/Yakutsk' = 'Asia/Yakutsk',
	'Asia/Vladivostok' = 'Asia/Vladivostok',
	'Asia/Khandyga' = 'Asia/Khandyga',
	'Asia/Sakhalin' = 'Asia/Sakhalin',
	'Asia/Magadan' = 'Asia/Magadan',
	'Asia/Srednekolymsk' = 'Asia/Srednekolymsk',
	'Asia/Ust-Nera' = 'Asia/Ust-Nera',
	'Asia/Kamchatka' = 'Asia/Kamchatka',
	'Asia/Anadyr' = 'Asia/Anadyr',
	'Europe/Belgrade' = 'Europe/Belgrade',
	'Europe/Ljubljana' = 'Europe/Ljubljana',
	'Europe/Podgorica' = 'Europe/Podgorica',
	'Europe/Sarajevo' = 'Europe/Sarajevo',
	'Europe/Skopje' = 'Europe/Skopje',
	'Europe/Zagreb' = 'Europe/Zagreb',
	'Europe/Bratislava' = 'Europe/Bratislava',
	'Europe/Madrid' = 'Europe/Madrid',
	'Africa/Ceuta' = 'Africa/Ceuta',
	'Atlantic/Canary' = 'Atlantic/Canary',
	'Europe/Stockholm' = 'Europe/Stockholm',
	'Europe/Zurich' = 'Europe/Zurich',
	'Europe/Istanbul' = 'Europe/Istanbul',
	'Asia/Istanbul' = 'Asia/Istanbul',
	'Europe/Kiev' = 'Europe/Kiev',
	'Europe/Uzhgorod' = 'Europe/Uzhgorod',
	'Europe/Zaporozhye' = 'Europe/Zaporozhye',
	Factory = 'Factory',
	EST = 'EST',
	MST = 'MST',
	HST = 'HST',
	EST5EDT = 'EST5EDT',
	CST6CDT = 'CST6CDT',
	MST7MDT = 'MST7MDT',
	PST8PDT = 'PST8PDT',
	'America/New_York' = 'America/New_York',
	'America/Chicago' = 'America/Chicago',
	'America/North_Dakota/Center' = 'America/North_Dakota/Center',
	'America/North_Dakota/New_Salem' = 'America/North_Dakota/New_Salem',
	'America/North_Dakota/Beulah' = 'America/North_Dakota/Beulah',
	'America/Denver' = 'America/Denver',
	'America/Los_Angeles' = 'America/Los_Angeles',
	'America/Juneau' = 'America/Juneau',
	'America/Sitka' = 'America/Sitka',
	'America/Metlakatla' = 'America/Metlakatla',
	'America/Yakutat' = 'America/Yakutat',
	'America/Anchorage' = 'America/Anchorage',
	'America/Nome' = 'America/Nome',
	'America/Adak' = 'America/Adak',
	'Pacific/Honolulu' = 'Pacific/Honolulu',
	'America/Phoenix' = 'America/Phoenix',
	'America/Boise' = 'America/Boise',
	'America/Indiana/Indianapolis' = 'America/Indiana/Indianapolis',
	'America/Indiana/Marengo' = 'America/Indiana/Marengo',
	'America/Indiana/Vincennes' = 'America/Indiana/Vincennes',
	'America/Indiana/Tell_City' = 'America/Indiana/Tell_City',
	'America/Indiana/Petersburg' = 'America/Indiana/Petersburg',
	'America/Indiana/Knox' = 'America/Indiana/Knox',
	'America/Indiana/Winamac' = 'America/Indiana/Winamac',
	'America/Indiana/Vevay' = 'America/Indiana/Vevay',
	'America/Kentucky/Louisville' = 'America/Kentucky/Louisville',
	'America/Kentucky/Monticello' = 'America/Kentucky/Monticello',
	'America/Detroit' = 'America/Detroit',
	'America/Menominee' = 'America/Menominee',
	'America/St_Johns' = 'America/St_Johns',
	'America/Goose_Bay' = 'America/Goose_Bay',
	'America/Halifax' = 'America/Halifax',
	'America/Glace_Bay' = 'America/Glace_Bay',
	'America/Moncton' = 'America/Moncton',
	'America/Blanc-Sablon' = 'America/Blanc-Sablon',
	'America/Toronto' = 'America/Toronto',
	'America/Thunder_Bay' = 'America/Thunder_Bay',
	'America/Nipigon' = 'America/Nipigon',
	'America/Rainy_River' = 'America/Rainy_River',
	'America/Atikokan' = 'America/Atikokan',
	'America/Winnipeg' = 'America/Winnipeg',
	'America/Regina' = 'America/Regina',
	'America/Swift_Current' = 'America/Swift_Current',
	'America/Edmonton' = 'America/Edmonton',
	'America/Vancouver' = 'America/Vancouver',
	'America/Dawson_Creek' = 'America/Dawson_Creek',
	'America/Fort_Nelson' = 'America/Fort_Nelson',
	'America/Creston' = 'America/Creston',
	'America/Pangnirtung' = 'America/Pangnirtung',
	'America/Iqaluit' = 'America/Iqaluit',
	'America/Resolute' = 'America/Resolute',
	'America/Rankin_Inlet' = 'America/Rankin_Inlet',
	'America/Cambridge_Bay' = 'America/Cambridge_Bay',
	'America/Yellowknife' = 'America/Yellowknife',
	'America/Inuvik' = 'America/Inuvik',
	'America/Whitehorse' = 'America/Whitehorse',
	'America/Dawson' = 'America/Dawson',
	'America/Cancun' = 'America/Cancun',
	'America/Merida' = 'America/Merida',
	'America/Matamoros' = 'America/Matamoros',
	'America/Monterrey' = 'America/Monterrey',
	'America/Mexico_City' = 'America/Mexico_City',
	'America/Ojinaga' = 'America/Ojinaga',
	'America/Chihuahua' = 'America/Chihuahua',
	'America/Hermosillo' = 'America/Hermosillo',
	'America/Mazatlan' = 'America/Mazatlan',
	'America/Bahia_Banderas' = 'America/Bahia_Banderas',
	'America/Tijuana' = 'America/Tijuana',
	'America/Nassau' = 'America/Nassau',
	'America/Barbados' = 'America/Barbados',
	'America/Belize' = 'America/Belize',
	'Atlantic/Bermuda' = 'Atlantic/Bermuda',
	'America/Costa_Rica' = 'America/Costa_Rica',
	'America/Havana' = 'America/Havana',
	'America/Santo_Domingo' = 'America/Santo_Domingo',
	'America/El_Salvador' = 'America/El_Salvador',
	'America/Guatemala' = 'America/Guatemala',
	'America/Port-au-Prince' = 'America/Port-au-Prince',
	'America/Tegucigalpa' = 'America/Tegucigalpa',
	'America/Jamaica' = 'America/Jamaica',
	'America/Martinique' = 'America/Martinique',
	'America/Managua' = 'America/Managua',
	'America/Panama' = 'America/Panama',
	'America/Cayman' = 'America/Cayman',
	'America/Puerto_Rico' = 'America/Puerto_Rico',
	'America/Miquelon' = 'America/Miquelon',
	'America/Grand_Turk' = 'America/Grand_Turk',
	'US/Pacific-New' = 'US/Pacific-New',
	'America/Argentina/Buenos_Aires' = 'America/Argentina/Buenos_Aires',
	'America/Argentina/Cordoba' = 'America/Argentina/Cordoba',
	'America/Argentina/Salta' = 'America/Argentina/Salta',
	'America/Argentina/Tucuman' = 'America/Argentina/Tucuman',
	'America/Argentina/La_Rioja' = 'America/Argentina/La_Rioja',
	'America/Argentina/San_Juan' = 'America/Argentina/San_Juan',
	'America/Argentina/Jujuy' = 'America/Argentina/Jujuy',
	'America/Argentina/Catamarca' = 'America/Argentina/Catamarca',
	'America/Argentina/Mendoza' = 'America/Argentina/Mendoza',
	'America/Argentina/San_Luis' = 'America/Argentina/San_Luis',
	'America/Argentina/Rio_Gallegos' = 'America/Argentina/Rio_Gallegos',
	'America/Argentina/Ushuaia' = 'America/Argentina/Ushuaia',
	'America/Aruba' = 'America/Aruba',
	'America/La_Paz' = 'America/La_Paz',
	'America/Noronha' = 'America/Noronha',
	'America/Belem' = 'America/Belem',
	'America/Santarem' = 'America/Santarem',
	'America/Fortaleza' = 'America/Fortaleza',
	'America/Recife' = 'America/Recife',
	'America/Araguaina' = 'America/Araguaina',
	'America/Maceio' = 'America/Maceio',
	'America/Bahia' = 'America/Bahia',
	'America/Sao_Paulo' = 'America/Sao_Paulo',
	'America/Campo_Grande' = 'America/Campo_Grande',
	'America/Cuiaba' = 'America/Cuiaba',
	'America/Porto_Velho' = 'America/Porto_Velho',
	'America/Boa_Vista' = 'America/Boa_Vista',
	'America/Manaus' = 'America/Manaus',
	'America/Eirunepe' = 'America/Eirunepe',
	'America/Rio_Branco' = 'America/Rio_Branco',
	'America/Santiago' = 'America/Santiago',
	'America/Punta_Arenas' = 'America/Punta_Arenas',
	'Pacific/Easter' = 'Pacific/Easter',
	'Antarctica/Palmer' = 'Antarctica/Palmer',
	'America/Bogota' = 'America/Bogota',
	'America/Curacao' = 'America/Curacao',
	'America/Lower_Princes' = 'America/Lower_Princes',
	'America/Kralendijk' = 'America/Kralendijk',
	'America/Guayaquil' = 'America/Guayaquil',
	'Pacific/Galapagos' = 'Pacific/Galapagos',
	'Atlantic/Stanley' = 'Atlantic/Stanley',
	'America/Cayenne' = 'America/Cayenne',
	'America/Guyana' = 'America/Guyana',
	'America/Asuncion' = 'America/Asuncion',
	'America/Lima' = 'America/Lima',
	'Atlantic/South_Georgia' = 'Atlantic/South_Georgia',
	'America/Paramaribo' = 'America/Paramaribo',
	'America/Port_of_Spain' = 'America/Port_of_Spain',
	'America/Anguilla' = 'America/Anguilla',
	'America/Antigua' = 'America/Antigua',
	'America/Dominica' = 'America/Dominica',
	'America/Grenada' = 'America/Grenada',
	'America/Guadeloupe' = 'America/Guadeloupe',
	'America/Marigot' = 'America/Marigot',
	'America/Montserrat' = 'America/Montserrat',
	'America/St_Barthelemy' = 'America/St_Barthelemy',
	'America/St_Kitts' = 'America/St_Kitts',
	'America/St_Lucia' = 'America/St_Lucia',
	'America/St_Thomas' = 'America/St_Thomas',
	'America/St_Vincent' = 'America/St_Vincent',
	'America/Tortola' = 'America/Tortola',
	'America/Montevideo' = 'America/Montevideo',
	'America/Caracas' = 'America/Caracas',
}

export const TimeZone: Record<string, string> = {
	'Africa/Algiers': 'Africa/Algiers',
	'Atlantic/Cape_Verde': 'Atlantic/Cape_Verde',
	'Africa/Ndjamena': 'Africa/Ndjamena',
	'Africa/Abidjan': 'Africa/Abidjan',
	'Africa/Bamako': 'Africa/Bamako',
	'Africa/Banjul': 'Africa/Banjul',
	'Africa/Conakry': 'Africa/Conakry',
	'Africa/Dakar': 'Africa/Dakar',
	'Africa/Freetown': 'Africa/Freetown',
	'Africa/Lome': 'Africa/Lome',
	'Africa/Nouakchott': 'Africa/Nouakchott',
	'Africa/Ouagadougou': 'Africa/Ouagadougou',
	'Atlantic/St_Helena': 'Atlantic/St_Helena',
	'Africa/Cairo': 'Africa/Cairo',
	'Africa/Accra': 'Africa/Accra',
	'Africa/Bissau': 'Africa/Bissau',
	'Africa/Nairobi': 'Africa/Nairobi',
	'Africa/Addis_Ababa': 'Africa/Addis_Ababa',
	'Africa/Asmara': 'Africa/Asmara',
	'Africa/Dar_es_Salaam': 'Africa/Dar_es_Salaam',
	'Africa/Djibouti': 'Africa/Djibouti',
	'Africa/Kampala': 'Africa/Kampala',
	'Africa/Mogadishu': 'Africa/Mogadishu',
	'Indian/Antananarivo': 'Indian/Antananarivo',
	'Indian/Comoro': 'Indian/Comoro',
	'Indian/Mayotte': 'Indian/Mayotte',
	'Africa/Monrovia': 'Africa/Monrovia',
	'Africa/Tripoli': 'Africa/Tripoli',
	'Indian/Mauritius': 'Indian/Mauritius',
	'Africa/Casablanca': 'Africa/Casablanca',
	'Africa/El_Aaiun': 'Africa/El_Aaiun',
	'Africa/Maputo': 'Africa/Maputo',
	'Africa/Blantyre': 'Africa/Blantyre',
	'Africa/Bujumbura': 'Africa/Bujumbura',
	'Africa/Gaborone': 'Africa/Gaborone',
	'Africa/Harare': 'Africa/Harare',
	'Africa/Kigali': 'Africa/Kigali',
	'Africa/Lubumbashi': 'Africa/Lubumbashi',
	'Africa/Lusaka': 'Africa/Lusaka',
	'Africa/Windhoek': 'Africa/Windhoek',
	'Africa/Lagos': 'Africa/Lagos',
	'Africa/Bangui': 'Africa/Bangui',
	'Africa/Brazzaville': 'Africa/Brazzaville',
	'Africa/Douala': 'Africa/Douala',
	'Africa/Kinshasa': 'Africa/Kinshasa',
	'Africa/Libreville': 'Africa/Libreville',
	'Africa/Luanda': 'Africa/Luanda',
	'Africa/Malabo': 'Africa/Malabo',
	'Africa/Niamey': 'Africa/Niamey',
	'Africa/Porto-Novo': 'Africa/Porto-Novo',
	'Indian/Reunion': 'Indian/Reunion',
	'Africa/Sao_Tome': 'Africa/Sao_Tome',
	'Indian/Mahe': 'Indian/Mahe',
	'Africa/Johannesburg': 'Africa/Johannesburg',
	'Africa/Maseru': 'Africa/Maseru',
	'Africa/Mbabane': 'Africa/Mbabane',
	'Africa/Khartoum': 'Africa/Khartoum',
	'Africa/Juba': 'Africa/Juba',
	'Africa/Tunis': 'Africa/Tunis',
	'Antarctica/Casey': 'Antarctica/Casey',
	'Antarctica/Davis': 'Antarctica/Davis',
	'Antarctica/Mawson': 'Antarctica/Mawson',
	'Indian/Kerguelen': 'Indian/Kerguelen',
	'Antarctica/DumontDUrville': 'Antarctica/DumontDUrville',
	'Antarctica/Syowa': 'Antarctica/Syowa',
	'Antarctica/Troll': 'Antarctica/Troll',
	'Antarctica/Vostok': 'Antarctica/Vostok',
	'Antarctica/Rothera': 'Antarctica/Rothera',
	'Asia/Kabul': 'Asia/Kabul',
	'Asia/Yerevan': 'Asia/Yerevan',
	'Asia/Baku': 'Asia/Baku',
	'Asia/Dhaka': 'Asia/Dhaka',
	'Asia/Thimphu': 'Asia/Thimphu',
	'Indian/Chagos': 'Indian/Chagos',
	'Asia/Brunei': 'Asia/Brunei',
	'Asia/Yangon': 'Asia/Yangon',
	'Asia/Shanghai': 'Asia/Shanghai',
	'Asia/Urumqi': 'Asia/Urumqi',
	'Asia/Hong_Kong': 'Asia/Hong_Kong',
	'Asia/Taipei': 'Asia/Taipei',
	'Asia/Macau': 'Asia/Macau',
	'Asia/Nicosia': 'Asia/Nicosia',
	'Asia/Famagusta': 'Asia/Famagusta',
	'Europe/Nicosia': 'Europe/Nicosia',
	'Asia/Tbilisi': 'Asia/Tbilisi',
	'Asia/Dili': 'Asia/Dili',
	'Asia/Kolkata': 'Asia/Kolkata',
	'Asia/Jakarta': 'Asia/Jakarta',
	'Asia/Pontianak': 'Asia/Pontianak',
	'Asia/Makassar': 'Asia/Makassar',
	'Asia/Jayapura': 'Asia/Jayapura',
	'Asia/Tehran': 'Asia/Tehran',
	'Asia/Baghdad': 'Asia/Baghdad',
	'Asia/Jerusalem': 'Asia/Jerusalem',
	'Asia/Tokyo': 'Asia/Tokyo',
	'Asia/Amman': 'Asia/Amman',
	'Asia/Almaty': 'Asia/Almaty',
	'Asia/Qyzylorda': 'Asia/Qyzylorda',
	'Asia/Qostanay': 'Asia/Qostanay',
	'Asia/Aqtobe': 'Asia/Aqtobe',
	'Asia/Aqtau': 'Asia/Aqtau',
	'Asia/Atyrau': 'Asia/Atyrau',
	'Asia/Oral': 'Asia/Oral',
	'Asia/Bishkek': 'Asia/Bishkek',
	'Asia/Seoul': 'Asia/Seoul',
	'Asia/Pyongyang': 'Asia/Pyongyang',
	'Asia/Beirut': 'Asia/Beirut',
	'Asia/Kuala_Lumpur': 'Asia/Kuala_Lumpur',
	'Asia/Kuching': 'Asia/Kuching',
	'Indian/Maldives': 'Indian/Maldives',
	'Asia/Hovd': 'Asia/Hovd',
	'Asia/Ulaanbaatar': 'Asia/Ulaanbaatar',
	'Asia/Choibalsan': 'Asia/Choibalsan',
	'Asia/Kathmandu': 'Asia/Kathmandu',
	'Asia/Karachi': 'Asia/Karachi',
	'Asia/Gaza': 'Asia/Gaza',
	'Asia/Hebron': 'Asia/Hebron',
	'Asia/Manila': 'Asia/Manila',
	'Asia/Qatar': 'Asia/Qatar',
	'Asia/Bahrain': 'Asia/Bahrain',
	'Asia/Riyadh': 'Asia/Riyadh',
	'Asia/Aden': 'Asia/Aden',
	'Asia/Kuwait': 'Asia/Kuwait',
	'Asia/Singapore': 'Asia/Singapore',
	'Asia/Colombo': 'Asia/Colombo',
	'Asia/Damascus': 'Asia/Damascus',
	'Asia/Dushanbe': 'Asia/Dushanbe',
	'Asia/Bangkok': 'Asia/Bangkok',
	'Asia/Phnom_Penh': 'Asia/Phnom_Penh',
	'Asia/Vientiane': 'Asia/Vientiane',
	'Asia/Ashgabat': 'Asia/Ashgabat',
	'Asia/Dubai': 'Asia/Dubai',
	'Asia/Muscat': 'Asia/Muscat',
	'Asia/Samarkand': 'Asia/Samarkand',
	'Asia/Tashkent': 'Asia/Tashkent',
	'Asia/Ho_Chi_Minh': 'Asia/Ho_Chi_Minh',
	'Australia/Darwin': 'Australia/Darwin',
	'Australia/Perth': 'Australia/Perth',
	'Australia/Eucla': 'Australia/Eucla',
	'Australia/Brisbane': 'Australia/Brisbane',
	'Australia/Lindeman': 'Australia/Lindeman',
	'Australia/Adelaide': 'Australia/Adelaide',
	'Australia/Hobart': 'Australia/Hobart',
	'Australia/Currie': 'Australia/Currie',
	'Australia/Melbourne': 'Australia/Melbourne',
	'Australia/Sydney': 'Australia/Sydney',
	'Australia/Broken_Hill': 'Australia/Broken_Hill',
	'Australia/Lord_Howe': 'Australia/Lord_Howe',
	'Antarctica/Macquarie': 'Antarctica/Macquarie',
	'Indian/Christmas': 'Indian/Christmas',
	'Indian/Cocos': 'Indian/Cocos',
	'Pacific/Fiji': 'Pacific/Fiji',
	'Pacific/Gambier': 'Pacific/Gambier',
	'Pacific/Marquesas': 'Pacific/Marquesas',
	'Pacific/Tahiti': 'Pacific/Tahiti',
	'Pacific/Guam': 'Pacific/Guam',
	'Pacific/Saipan': 'Pacific/Saipan',
	'Pacific/Tarawa': 'Pacific/Tarawa',
	'Pacific/Enderbury': 'Pacific/Enderbury',
	'Pacific/Kiritimati': 'Pacific/Kiritimati',
	'Pacific/Majuro': 'Pacific/Majuro',
	'Pacific/Kwajalein': 'Pacific/Kwajalein',
	'Pacific/Chuuk': 'Pacific/Chuuk',
	'Pacific/Pohnpei': 'Pacific/Pohnpei',
	'Pacific/Kosrae': 'Pacific/Kosrae',
	'Pacific/Nauru': 'Pacific/Nauru',
	'Pacific/Noumea': 'Pacific/Noumea',
	'Pacific/Auckland': 'Pacific/Auckland',
	'Pacific/Chatham': 'Pacific/Chatham',
	'Antarctica/McMurdo': 'Antarctica/McMurdo',
	'Pacific/Rarotonga': 'Pacific/Rarotonga',
	'Pacific/Niue': 'Pacific/Niue',
	'Pacific/Norfolk': 'Pacific/Norfolk',
	'Pacific/Palau': 'Pacific/Palau',
	'Pacific/Port_Moresby': 'Pacific/Port_Moresby',
	'Pacific/Bougainville': 'Pacific/Bougainville',
	'Pacific/Pitcairn': 'Pacific/Pitcairn',
	'Pacific/Pago_Pago': 'Pacific/Pago_Pago',
	'Pacific/Midway': 'Pacific/Midway',
	'Pacific/Apia': 'Pacific/Apia',
	'Pacific/Guadalcanal': 'Pacific/Guadalcanal',
	'Pacific/Fakaofo': 'Pacific/Fakaofo',
	'Pacific/Tongatapu': 'Pacific/Tongatapu',
	'Pacific/Funafuti': 'Pacific/Funafuti',
	'Pacific/Wake': 'Pacific/Wake',
	'Pacific/Efate': 'Pacific/Efate',
	'Pacific/Wallis': 'Pacific/Wallis',
	'Africa/Asmera': 'Africa/Asmera',
	'Africa/Timbuktu': 'Africa/Timbuktu',
	'America/Argentina/ComodRivadavia': 'America/Argentina/ComodRivadavia',
	'America/Atka': 'America/Atka',
	'America/Buenos_Aires': 'America/Buenos_Aires',
	'America/Catamarca': 'America/Catamarca',
	'America/Coral_Harbour': 'America/Coral_Harbour',
	'America/Cordoba': 'America/Cordoba',
	'America/Ensenada': 'America/Ensenada',
	'America/Fort_Wayne': 'America/Fort_Wayne',
	'America/Indianapolis': 'America/Indianapolis',
	'America/Jujuy': 'America/Jujuy',
	'America/Knox_IN': 'America/Knox_IN',
	'America/Louisville': 'America/Louisville',
	'America/Mendoza': 'America/Mendoza',
	'America/Montreal': 'America/Montreal',
	'America/Porto_Acre': 'America/Porto_Acre',
	'America/Rosario': 'America/Rosario',
	'America/Santa_Isabel': 'America/Santa_Isabel',
	'America/Shiprock': 'America/Shiprock',
	'America/Virgin': 'America/Virgin',
	'Antarctica/South_Pole': 'Antarctica/South_Pole',
	'Asia/Ashkhabad': 'Asia/Ashkhabad',
	'Asia/Calcutta': 'Asia/Calcutta',
	'Asia/Chongqing': 'Asia/Chongqing',
	'Asia/Chungking': 'Asia/Chungking',
	'Asia/Dacca': 'Asia/Dacca',
	'Asia/Harbin': 'Asia/Harbin',
	'Asia/Kashgar': 'Asia/Kashgar',
	'Asia/Katmandu': 'Asia/Katmandu',
	'Asia/Macao': 'Asia/Macao',
	'Asia/Rangoon': 'Asia/Rangoon',
	'Asia/Saigon': 'Asia/Saigon',
	'Asia/Tel_Aviv': 'Asia/Tel_Aviv',
	'Asia/Thimbu': 'Asia/Thimbu',
	'Asia/Ujung_Pandang': 'Asia/Ujung_Pandang',
	'Asia/Ulan_Bator': 'Asia/Ulan_Bator',
	'Atlantic/Faeroe': 'Atlantic/Faeroe',
	'Atlantic/Jan_Mayen': 'Atlantic/Jan_Mayen',
	'Australia/ACT': 'Australia/ACT',
	'Australia/Canberra': 'Australia/Canberra',
	'Australia/LHI': 'Australia/LHI',
	'Australia/NSW': 'Australia/NSW',
	'Australia/North': 'Australia/North',
	'Australia/Queensland': 'Australia/Queensland',
	'Australia/South': 'Australia/South',
	'Australia/Tasmania': 'Australia/Tasmania',
	'Australia/Victoria': 'Australia/Victoria',
	'Australia/West': 'Australia/West',
	'Australia/Yancowinna': 'Australia/Yancowinna',
	'Brazil/Acre': 'Brazil/Acre',
	'Brazil/DeNoronha': 'Brazil/DeNoronha',
	'Brazil/East': 'Brazil/East',
	'Brazil/West': 'Brazil/West',
	'Canada/Atlantic': 'Canada/Atlantic',
	'Canada/Central': 'Canada/Central',
	'Canada/Eastern': 'Canada/Eastern',
	'Canada/Mountain': 'Canada/Mountain',
	'Canada/Newfoundland': 'Canada/Newfoundland',
	'Canada/Pacific': 'Canada/Pacific',
	'Canada/Saskatchewan': 'Canada/Saskatchewan',
	'Canada/Yukon': 'Canada/Yukon',
	'Chile/Continental': 'Chile/Continental',
	'Chile/EasterIsland': 'Chile/EasterIsland',
	Cuba: 'Cuba',
	Egypt: 'Egypt',
	Eire: 'Eire',
	'Etc/UCT': 'Etc/UCT',
	'Europe/Belfast': 'Europe/Belfast',
	'Europe/Tiraspol': 'Europe/Tiraspol',
	GB: 'GB',
	'GB-Eire': 'GB-Eire',
	'GMT+0': 'GMT+0',
	'GMT-0': 'GMT-0',
	GMT0: 'GMT0',
	Greenwich: 'Greenwich',
	Hongkong: 'Hongkong',
	Iceland: 'Iceland',
	Iran: 'Iran',
	Israel: 'Israel',
	Jamaica: 'Jamaica',
	Japan: 'Japan',
	Kwajalein: 'Kwajalein',
	Libya: 'Libya',
	'Mexico/BajaNorte': 'Mexico/BajaNorte',
	'Mexico/BajaSur': 'Mexico/BajaSur',
	'Mexico/General': 'Mexico/General',
	NZ: 'NZ',
	'NZ-CHAT': 'NZ-CHAT',
	Navajo: 'Navajo',
	PRC: 'PRC',
	'Pacific/Johnston': 'Pacific/Johnston',
	'Pacific/Ponape': 'Pacific/Ponape',
	'Pacific/Samoa': 'Pacific/Samoa',
	'Pacific/Truk': 'Pacific/Truk',
	'Pacific/Yap': 'Pacific/Yap',
	Poland: 'Poland',
	Portugal: 'Portugal',
	ROC: 'ROC',
	ROK: 'ROK',
	Singapore: 'Singapore',
	Turkey: 'Turkey',
	UCT: 'UCT',
	'US/Alaska': 'US/Alaska',
	'US/Aleutian': 'US/Aleutian',
	'US/Arizona': 'US/Arizona',
	'US/Central': 'US/Central',
	'US/East-Indiana': 'US/East-Indiana',
	'US/Eastern': 'US/Eastern',
	'US/Hawaii': 'US/Hawaii',
	'US/Indiana-Starke': 'US/Indiana-Starke',
	'US/Michigan': 'US/Michigan',
	'US/Mountain': 'US/Mountain',
	'US/Pacific': 'US/Pacific',
	'US/Samoa': 'US/Samoa',
	UTC: 'UTC',
	Universal: 'Universal',
	'W-SU': 'W-SU',
	Zulu: 'Zulu',
	'Etc/GMT': 'Etc/GMT',
	'Etc/UTC': 'Etc/UTC',
	GMT: 'GMT',
	'Etc/Universal': 'Etc/Universal',
	'Etc/Zulu': 'Etc/Zulu',
	'Etc/Greenwich': 'Etc/Greenwich',
	'Etc/GMT-0': 'Etc/GMT-0',
	'Etc/GMT+0': 'Etc/GMT+0',
	'Etc/GMT0': 'Etc/GMT0',
	'Etc/GMT-14': 'Etc/GMT-14',
	'Etc/GMT-13': 'Etc/GMT-13',
	'Etc/GMT-12': 'Etc/GMT-12',
	'Etc/GMT-11': 'Etc/GMT-11',
	'Etc/GMT-10': 'Etc/GMT-10',
	'Etc/GMT-9': 'Etc/GMT-9',
	'Etc/GMT-8': 'Etc/GMT-8',
	'Etc/GMT-7': 'Etc/GMT-7',
	'Etc/GMT-6': 'Etc/GMT-6',
	'Etc/GMT-5': 'Etc/GMT-5',
	'Etc/GMT-4': 'Etc/GMT-4',
	'Etc/GMT-3': 'Etc/GMT-3',
	'Etc/GMT-2': 'Etc/GMT-2',
	'Etc/GMT-1': 'Etc/GMT-1',
	'Etc/GMT+1': 'Etc/GMT+1',
	'Etc/GMT+2': 'Etc/GMT+2',
	'Etc/GMT+3': 'Etc/GMT+3',
	'Etc/GMT+4': 'Etc/GMT+4',
	'Etc/GMT+5': 'Etc/GMT+5',
	'Etc/GMT+6': 'Etc/GMT+6',
	'Etc/GMT+7': 'Etc/GMT+7',
	'Etc/GMT+8': 'Etc/GMT+8',
	'Etc/GMT+9': 'Etc/GMT+9',
	'Etc/GMT+10': 'Etc/GMT+10',
	'Etc/GMT+11': 'Etc/GMT+11',
	'Etc/GMT+12': 'Etc/GMT+12',
	'Europe/London': 'Europe/London',
	'Europe/Jersey': 'Europe/Jersey',
	'Europe/Guernsey': 'Europe/Guernsey',
	'Europe/Isle_of_Man': 'Europe/Isle_of_Man',
	'Europe/Dublin': 'Europe/Dublin',
	WET: 'WET',
	CET: 'CET',
	MET: 'MET',
	EET: 'EET',
	'Europe/Tirane': 'Europe/Tirane',
	'Europe/Andorra': 'Europe/Andorra',
	'Europe/Vienna': 'Europe/Vienna',
	'Europe/Minsk': 'Europe/Minsk',
	'Europe/Brussels': 'Europe/Brussels',
	'Europe/Sofia': 'Europe/Sofia',
	'Europe/Prague': 'Europe/Prague',
	'Europe/Copenhagen': 'Europe/Copenhagen',
	'Atlantic/Faroe': 'Atlantic/Faroe',
	'America/Danmarkshavn': 'America/Danmarkshavn',
	'America/Scoresbysund': 'America/Scoresbysund',
	'America/Godthab': 'America/Godthab',
	'America/Thule': 'America/Thule',
	'Europe/Tallinn': 'Europe/Tallinn',
	'Europe/Helsinki': 'Europe/Helsinki',
	'Europe/Mariehamn': 'Europe/Mariehamn',
	'Europe/Paris': 'Europe/Paris',
	'Europe/Berlin': 'Europe/Berlin',
	'Europe/Busingen': 'Europe/Busingen',
	'Europe/Gibraltar': 'Europe/Gibraltar',
	'Europe/Athens': 'Europe/Athens',
	'Europe/Budapest': 'Europe/Budapest',
	'Atlantic/Reykjavik': 'Atlantic/Reykjavik',
	'Europe/Rome': 'Europe/Rome',
	'Europe/Vatican': 'Europe/Vatican',
	'Europe/San_Marino': 'Europe/San_Marino',
	'Europe/Riga': 'Europe/Riga',
	'Europe/Vaduz': 'Europe/Vaduz',
	'Europe/Vilnius': 'Europe/Vilnius',
	'Europe/Luxembourg': 'Europe/Luxembourg',
	'Europe/Malta': 'Europe/Malta',
	'Europe/Chisinau': 'Europe/Chisinau',
	'Europe/Monaco': 'Europe/Monaco',
	'Europe/Amsterdam': 'Europe/Amsterdam',
	'Europe/Oslo': 'Europe/Oslo',
	'Arctic/Longyearbyen': 'Arctic/Longyearbyen',
	'Europe/Warsaw': 'Europe/Warsaw',
	'Europe/Lisbon': 'Europe/Lisbon',
	'Atlantic/Azores': 'Atlantic/Azores',
	'Atlantic/Madeira': 'Atlantic/Madeira',
	'Europe/Bucharest': 'Europe/Bucharest',
	'Europe/Kaliningrad': 'Europe/Kaliningrad',
	'Europe/Moscow': 'Europe/Moscow',
	'Europe/Simferopol': 'Europe/Simferopol',
	'Europe/Astrakhan': 'Europe/Astrakhan',
	'Europe/Volgograd': 'Europe/Volgograd',
	'Europe/Saratov': 'Europe/Saratov',
	'Europe/Kirov': 'Europe/Kirov',
	'Europe/Samara': 'Europe/Samara',
	'Europe/Ulyanovsk': 'Europe/Ulyanovsk',
	'Asia/Yekaterinburg': 'Asia/Yekaterinburg',
	'Asia/Omsk': 'Asia/Omsk',
	'Asia/Barnaul': 'Asia/Barnaul',
	'Asia/Novosibirsk': 'Asia/Novosibirsk',
	'Asia/Tomsk': 'Asia/Tomsk',
	'Asia/Novokuznetsk': 'Asia/Novokuznetsk',
	'Asia/Krasnoyarsk': 'Asia/Krasnoyarsk',
	'Asia/Irkutsk': 'Asia/Irkutsk',
	'Asia/Chita': 'Asia/Chita',
	'Asia/Yakutsk': 'Asia/Yakutsk',
	'Asia/Vladivostok': 'Asia/Vladivostok',
	'Asia/Khandyga': 'Asia/Khandyga',
	'Asia/Sakhalin': 'Asia/Sakhalin',
	'Asia/Magadan': 'Asia/Magadan',
	'Asia/Srednekolymsk': 'Asia/Srednekolymsk',
	'Asia/Ust-Nera': 'Asia/Ust-Nera',
	'Asia/Kamchatka': 'Asia/Kamchatka',
	'Asia/Anadyr': 'Asia/Anadyr',
	'Europe/Belgrade': 'Europe/Belgrade',
	'Europe/Ljubljana': 'Europe/Ljubljana',
	'Europe/Podgorica': 'Europe/Podgorica',
	'Europe/Sarajevo': 'Europe/Sarajevo',
	'Europe/Skopje': 'Europe/Skopje',
	'Europe/Zagreb': 'Europe/Zagreb',
	'Europe/Bratislava': 'Europe/Bratislava',
	'Europe/Madrid': 'Europe/Madrid',
	'Africa/Ceuta': 'Africa/Ceuta',
	'Atlantic/Canary': 'Atlantic/Canary',
	'Europe/Stockholm': 'Europe/Stockholm',
	'Europe/Zurich': 'Europe/Zurich',
	'Europe/Istanbul': 'Europe/Istanbul',
	'Asia/Istanbul': 'Asia/Istanbul',
	'Europe/Kiev': 'Europe/Kiev',
	'Europe/Uzhgorod': 'Europe/Uzhgorod',
	'Europe/Zaporozhye': 'Europe/Zaporozhye',
	Factory: 'Factory',
	EST: 'EST',
	MST: 'MST',
	HST: 'HST',
	EST5EDT: 'EST5EDT',
	CST6CDT: 'CST6CDT',
	MST7MDT: 'MST7MDT',
	PST8PDT: 'PST8PDT',
	'America/New_York': 'America/New_York',
	'America/Chicago': 'America/Chicago',
	'America/North_Dakota/Center': 'America/North_Dakota/Center',
	'America/North_Dakota/New_Salem': 'America/North_Dakota/New_Salem',
	'America/North_Dakota/Beulah': 'America/North_Dakota/Beulah',
	'America/Denver': 'America/Denver',
	'America/Los_Angeles': 'America/Los_Angeles',
	'America/Juneau': 'America/Juneau',
	'America/Sitka': 'America/Sitka',
	'America/Metlakatla': 'America/Metlakatla',
	'America/Yakutat': 'America/Yakutat',
	'America/Anchorage': 'America/Anchorage',
	'America/Nome': 'America/Nome',
	'America/Adak': 'America/Adak',
	'Pacific/Honolulu': 'Pacific/Honolulu',
	'America/Phoenix': 'America/Phoenix',
	'America/Boise': 'America/Boise',
	'America/Indiana/Indianapolis': 'America/Indiana/Indianapolis',
	'America/Indiana/Marengo': 'America/Indiana/Marengo',
	'America/Indiana/Vincennes': 'America/Indiana/Vincennes',
	'America/Indiana/Tell_City': 'America/Indiana/Tell_City',
	'America/Indiana/Petersburg': 'America/Indiana/Petersburg',
	'America/Indiana/Knox': 'America/Indiana/Knox',
	'America/Indiana/Winamac': 'America/Indiana/Winamac',
	'America/Indiana/Vevay': 'America/Indiana/Vevay',
	'America/Kentucky/Louisville': 'America/Kentucky/Louisville',
	'America/Kentucky/Monticello': 'America/Kentucky/Monticello',
	'America/Detroit': 'America/Detroit',
	'America/Menominee': 'America/Menominee',
	'America/St_Johns': 'America/St_Johns',
	'America/Goose_Bay': 'America/Goose_Bay',
	'America/Halifax': 'America/Halifax',
	'America/Glace_Bay': 'America/Glace_Bay',
	'America/Moncton': 'America/Moncton',
	'America/Blanc-Sablon': 'America/Blanc-Sablon',
	'America/Toronto': 'America/Toronto',
	'America/Thunder_Bay': 'America/Thunder_Bay',
	'America/Nipigon': 'America/Nipigon',
	'America/Rainy_River': 'America/Rainy_River',
	'America/Atikokan': 'America/Atikokan',
	'America/Winnipeg': 'America/Winnipeg',
	'America/Regina': 'America/Regina',
	'America/Swift_Current': 'America/Swift_Current',
	'America/Edmonton': 'America/Edmonton',
	'America/Vancouver': 'America/Vancouver',
	'America/Dawson_Creek': 'America/Dawson_Creek',
	'America/Fort_Nelson': 'America/Fort_Nelson',
	'America/Creston': 'America/Creston',
	'America/Pangnirtung': 'America/Pangnirtung',
	'America/Iqaluit': 'America/Iqaluit',
	'America/Resolute': 'America/Resolute',
	'America/Rankin_Inlet': 'America/Rankin_Inlet',
	'America/Cambridge_Bay': 'America/Cambridge_Bay',
	'America/Yellowknife': 'America/Yellowknife',
	'America/Inuvik': 'America/Inuvik',
	'America/Whitehorse': 'America/Whitehorse',
	'America/Dawson': 'America/Dawson',
	'America/Cancun': 'America/Cancun',
	'America/Merida': 'America/Merida',
	'America/Matamoros': 'America/Matamoros',
	'America/Monterrey': 'America/Monterrey',
	'America/Mexico_City': 'America/Mexico_City',
	'America/Ojinaga': 'America/Ojinaga',
	'America/Chihuahua': 'America/Chihuahua',
	'America/Hermosillo': 'America/Hermosillo',
	'America/Mazatlan': 'America/Mazatlan',
	'America/Bahia_Banderas': 'America/Bahia_Banderas',
	'America/Tijuana': 'America/Tijuana',
	'America/Nassau': 'America/Nassau',
	'America/Barbados': 'America/Barbados',
	'America/Belize': 'America/Belize',
	'Atlantic/Bermuda': 'Atlantic/Bermuda',
	'America/Costa_Rica': 'America/Costa_Rica',
	'America/Havana': 'America/Havana',
	'America/Santo_Domingo': 'America/Santo_Domingo',
	'America/El_Salvador': 'America/El_Salvador',
	'America/Guatemala': 'America/Guatemala',
	'America/Port-au-Prince': 'America/Port-au-Prince',
	'America/Tegucigalpa': 'America/Tegucigalpa',
	'America/Jamaica': 'America/Jamaica',
	'America/Martinique': 'America/Martinique',
	'America/Managua': 'America/Managua',
	'America/Panama': 'America/Panama',
	'America/Cayman': 'America/Cayman',
	'America/Puerto_Rico': 'America/Puerto_Rico',
	'America/Miquelon': 'America/Miquelon',
	'America/Grand_Turk': 'America/Grand_Turk',
	'US/Pacific-New': 'US/Pacific-New',
	'America/Argentina/Buenos_Aires': 'America/Argentina/Buenos_Aires',
	'America/Argentina/Cordoba': 'America/Argentina/Cordoba',
	'America/Argentina/Salta': 'America/Argentina/Salta',
	'America/Argentina/Tucuman': 'America/Argentina/Tucuman',
	'America/Argentina/La_Rioja': 'America/Argentina/La_Rioja',
	'America/Argentina/San_Juan': 'America/Argentina/San_Juan',
	'America/Argentina/Jujuy': 'America/Argentina/Jujuy',
	'America/Argentina/Catamarca': 'America/Argentina/Catamarca',
	'America/Argentina/Mendoza': 'America/Argentina/Mendoza',
	'America/Argentina/San_Luis': 'America/Argentina/San_Luis',
	'America/Argentina/Rio_Gallegos': 'America/Argentina/Rio_Gallegos',
	'America/Argentina/Ushuaia': 'America/Argentina/Ushuaia',
	'America/Aruba': 'America/Aruba',
	'America/La_Paz': 'America/La_Paz',
	'America/Noronha': 'America/Noronha',
	'America/Belem': 'America/Belem',
	'America/Santarem': 'America/Santarem',
	'America/Fortaleza': 'America/Fortaleza',
	'America/Recife': 'America/Recife',
	'America/Araguaina': 'America/Araguaina',
	'America/Maceio': 'America/Maceio',
	'America/Bahia': 'America/Bahia',
	'America/Sao_Paulo': 'America/Sao_Paulo',
	'America/Campo_Grande': 'America/Campo_Grande',
	'America/Cuiaba': 'America/Cuiaba',
	'America/Porto_Velho': 'America/Porto_Velho',
	'America/Boa_Vista': 'America/Boa_Vista',
	'America/Manaus': 'America/Manaus',
	'America/Eirunepe': 'America/Eirunepe',
	'America/Rio_Branco': 'America/Rio_Branco',
	'America/Santiago': 'America/Santiago',
	'America/Punta_Arenas': 'America/Punta_Arenas',
	'Pacific/Easter': 'Pacific/Easter',
	'Antarctica/Palmer': 'Antarctica/Palmer',
	'America/Bogota': 'America/Bogota',
	'America/Curacao': 'America/Curacao',
	'America/Lower_Princes': 'America/Lower_Princes',
	'America/Kralendijk': 'America/Kralendijk',
	'America/Guayaquil': 'America/Guayaquil',
	'Pacific/Galapagos': 'Pacific/Galapagos',
	'Atlantic/Stanley': 'Atlantic/Stanley',
	'America/Cayenne': 'America/Cayenne',
	'America/Guyana': 'America/Guyana',
	'America/Asuncion': 'America/Asuncion',
	'America/Lima': 'America/Lima',
	'Atlantic/South_Georgia': 'Atlantic/South_Georgia',
	'America/Paramaribo': 'America/Paramaribo',
	'America/Port_of_Spain': 'America/Port_of_Spain',
	'America/Anguilla': 'America/Anguilla',
	'America/Antigua': 'America/Antigua',
	'America/Dominica': 'America/Dominica',
	'America/Grenada': 'America/Grenada',
	'America/Guadeloupe': 'America/Guadeloupe',
	'America/Marigot': 'America/Marigot',
	'America/Montserrat': 'America/Montserrat',
	'America/St_Barthelemy': 'America/St_Barthelemy',
	'America/St_Kitts': 'America/St_Kitts',
	'America/St_Lucia': 'America/St_Lucia',
	'America/St_Thomas': 'America/St_Thomas',
	'America/St_Vincent': 'America/St_Vincent',
	'America/Tortola': 'America/Tortola',
	'America/Montevideo': 'America/Montevideo',
	'America/Caracas': 'America/Caracas',
};
